export const PLANS = [
  {
    key: "FREE",
    name: "Starter",
    price: 0,
    currency: "USD",
    period: "forever",
    description: "Perfect for getting started",
    features: [
      "Up to 50 work orders/month",
      "1 user account",
      "Basic customer tracking",
      "WhatsApp notifications",
      "PDF reports",
      "Customer portal",
    ],
    limits: { workOrders: 50, users: 1, branches: 1 },
    highlight: false,
    cta: "Current Plan",
  },
  {
    key: "PRO",
    name: "Pro",
    price: 29,
    currency: "USD",
    period: "month",
    description: "For growing repair shops",
    features: [
      "Unlimited work orders",
      "Up to 10 users",
      "Multi-branch support",
      "Email notifications (Resend)",
      "IMEI blacklist checks",
      "Advanced analytics & reports",
      "API access",
      "Priority support",
    ],
    limits: { workOrders: -1, users: 10, branches: 3 },
    highlight: true,
    cta: "Upgrade to Pro",
  },
  {
    key: "ENTERPRISE",
    name: "Enterprise",
    price: 79,
    currency: "USD",
    period: "month",
    description: "For large repair chains",
    features: [
      "Everything in Pro",
      "Unlimited users & branches",
      "Custom domain email",
      "Dedicated support manager",
      "Custom integrations",
      "White-label option",
      "SLA guarantee",
      "On-boarding assistance",
    ],
    limits: { workOrders: -1, users: -1, branches: -1 },
    highlight: false,
    cta: "Contact Sales",
  },
] as const;
