"use client";

import { createContext, useContext, useEffect, useState } from "react";

export type Lang = "en" | "fr" | "ar";

export const translations = {
  en: {
    // Nav
    workOrders: "Work Orders",
    spareParts: "Spare Parts",
    customers: "Customers",
    warranties: "Warranties",
    satisfaction: "Satisfaction",
    csvImport: "CSV Import",
    analytics: "Analytics",
    engineers: "Engineers",
    reports: "Reports",
    templates: "Templates",
    shops: "Shops",
    expenses: "Expenses",
    settings: "Settings",
    appointments: "Appointments",
    suppliers: "Suppliers",
    certification: "Certification",
    messages: "Messages",
    pricing: "Pricing",
    contracts: "Contracts",
    branches: "Branches",
    pointOfSale: "Point of Sale",
    shifts: "Shifts",
    academy: "Academy",
    // Sidebar actions
    notifications: "Notifications",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    installApp: "Install App",
    logout: "Log out",
    // Bottom nav
    orders: "Orders",
    parts: "Parts",
    // Notifications panel
    markAllRead: "Mark all read",
    noNotifications: "No notifications",
    // Session warning
    sessionExpiring: "Session expiring soon",
    sessionWarningBody: "You'll be signed out in {time} due to inactivity.",
    stayLoggedIn: "Stay logged in",
    // Dashboard / Work Orders list
    newWorkOrder: "New Work Order",
    searchWorkOrders: "Search by customer, phone, device, order #...",
    all: "All",
    noContact3d: "No contact 3d+",
    allBranches: "All Branches",
    totalOrders: "Total Orders",
    received: "Received",
    inProgress: "In Progress",
    ready: "Ready",
    revenue: "Revenue",
    delivered: "Delivered",
    cancelled: "Cancelled",
    todaysAppointments: "Today's Appointments",
    noAppointmentsToday: "No appointments today",
    recentActivity: "Recent Activity",
    noRecentActivity: "No recent activity",
    viewAll: "View all",
    noOrdersMatchSearch: "No orders match your search",
    noWorkOrdersYet: "No work orders yet",
    tryDifferentSearch: "Try a different search or filter",
    createFirstWorkOrder: "Create your first work order to get started",
    selectAll: "Select all",
    selected: "selected",
    changeStatus: "Change status...",
    apply: "Apply",
    assignEngineer: "Assign engineer...",
    assign: "Assign",
    exportBtn: "Export",
    deleteBtn: "Delete",
    columns: "Columns",
    orderHash: "Order #",
    customer: "Customer",
    device: "Device",
    fault: "Fault",
    status: "Status",
    assignedTo: "Assigned To",
    total: "Total",
    date: "Date",
    view: "View",
    prev: "Prev",
    next: "Next",
    page: "Page",
    showing: "Showing",
    deleteWorkOrders: "Delete work orders",
    cannotBeUndone: "This cannot be undone.",
    cancel: "Cancel",
    deleting: "Deleting...",
    morningBriefing: "Morning Briefing",
    justNow: "just now",
    mAgo: "m ago",
    hAgo: "h ago",
    dAgo: "d ago",
    // Work Order detail
    back: "Back",
    print: "Print",
    share: "Share",
    whatsapp: "WhatsApp",
    sendReminder: "Send Reminder",
    healthReport: "Health Report",
    edit: "Edit",
    reportBounce: "Report Bounce",
    startDiagnosis: "Start Diagnosis",
    startRepair: "Start Repair",
    markDone: "Mark Done",
    markDelivered: "Mark Delivered",
    deviceInformation: "Device Information",
    brand: "Brand",
    model: "Model",
    serialNumber: "Serial Number",
    imei: "IMEI",
    warrantyStart: "Warranty Start",
    warrantyEnd: "Warranty End",
    customerInformation: "Customer Information",
    draftMessage: "Draft Message",
    name: "Name",
    phone: "Phone",
    email: "Email",
    faultAndService: "Fault & Service",
    serviceType: "Service Type",
    repairType: "Repair Type",
    faultLevel: "Fault Level",
    appearance: "Appearance",
    faultDescription: "Fault Description",
    remarks: "Remarks",
    addPart: "Add Part",
    part: "Part",
    quantity: "Quantity",
    price: "Price",
    noPartsAdded: "No parts added yet.",
    attachments: "Attachments",
    uploadFile: "Upload File",
    noAttachments: "No attachments yet.",
    save: "Save",
    saving: "Saving...",
    adding: "Adding...",
    // Customers page
    addCustomer: "Add Customer",
    searchCustomers: "Search customers...",
    noCustomersFound: "No customers found",
    // Spare Parts page
    searchParts: "Search parts...",
    stock: "Stock",
    unitPrice: "Unit Price",
    partNumber: "Part Number",
    noPartsFound: "No parts found",
    lowStock: "Low stock",
  },
  fr: {
    workOrders: "Ordres de travail",
    spareParts: "Pièces détachées",
    customers: "Clients",
    warranties: "Garanties",
    satisfaction: "Satisfaction",
    csvImport: "Import CSV",
    analytics: "Analytique",
    engineers: "Techniciens",
    reports: "Rapports",
    templates: "Modèles",
    shops: "Boutiques",
    expenses: "Dépenses",
    settings: "Paramètres",
    appointments: "Rendez-vous",
    suppliers: "Fournisseurs",
    certification: "Certification",
    messages: "Messages",
    pricing: "Tarification",
    contracts: "Contrats",
    branches: "Succursales",
    pointOfSale: "Point de vente",
    shifts: "Quarts de travail",
    academy: "Académie",
    notifications: "Notifications",
    lightMode: "Mode clair",
    darkMode: "Mode sombre",
    installApp: "Installer",
    logout: "Déconnexion",
    orders: "Ordres",
    parts: "Pièces",
    markAllRead: "Tout marquer lu",
    noNotifications: "Aucune notification",
    sessionExpiring: "Session bientôt expirée",
    sessionWarningBody: "Vous serez déconnecté dans {time} en raison d'inactivité.",
    stayLoggedIn: "Rester connecté",
    // Dashboard / Work Orders list
    newWorkOrder: "Nouvel ordre",
    searchWorkOrders: "Rechercher par client, téléphone, appareil, n° ordre...",
    all: "Tout",
    noContact3d: "Sans contact 3j+",
    allBranches: "Toutes les succursales",
    totalOrders: "Total des ordres",
    received: "Reçu",
    inProgress: "En cours",
    ready: "Prêt",
    revenue: "Revenus",
    delivered: "Livré",
    cancelled: "Annulé",
    todaysAppointments: "Rendez-vous du jour",
    noAppointmentsToday: "Aucun rendez-vous aujourd'hui",
    recentActivity: "Activité récente",
    noRecentActivity: "Aucune activité récente",
    viewAll: "Voir tout",
    noOrdersMatchSearch: "Aucun ordre ne correspond à votre recherche",
    noWorkOrdersYet: "Aucun ordre de travail",
    tryDifferentSearch: "Essayez une autre recherche ou un autre filtre",
    createFirstWorkOrder: "Créez votre premier ordre pour commencer",
    selectAll: "Tout sélectionner",
    selected: "sélectionné(s)",
    changeStatus: "Changer le statut...",
    apply: "Appliquer",
    assignEngineer: "Assigner technicien...",
    assign: "Assigner",
    exportBtn: "Exporter",
    deleteBtn: "Supprimer",
    columns: "Colonnes",
    orderHash: "N° ordre",
    customer: "Client",
    device: "Appareil",
    fault: "Panne",
    status: "Statut",
    assignedTo: "Assigné à",
    total: "Total",
    date: "Date",
    view: "Voir",
    prev: "Préc.",
    next: "Suiv.",
    page: "Page",
    showing: "Affichage",
    deleteWorkOrders: "Supprimer les ordres",
    cannotBeUndone: "Cette action est irréversible.",
    cancel: "Annuler",
    deleting: "Suppression...",
    morningBriefing: "Briefing du matin",
    justNow: "à l'instant",
    mAgo: "min",
    hAgo: "h",
    dAgo: "j",
    // Work Order detail
    back: "Retour",
    print: "Imprimer",
    share: "Partager",
    whatsapp: "WhatsApp",
    sendReminder: "Envoyer rappel",
    healthReport: "Rapport de santé",
    edit: "Modifier",
    reportBounce: "Signaler retour",
    startDiagnosis: "Commencer diagnostic",
    startRepair: "Commencer réparation",
    markDone: "Marquer terminé",
    markDelivered: "Marquer livré",
    deviceInformation: "Informations appareil",
    brand: "Marque",
    model: "Modèle",
    serialNumber: "Numéro de série",
    imei: "IMEI",
    warrantyStart: "Début garantie",
    warrantyEnd: "Fin garantie",
    customerInformation: "Informations client",
    draftMessage: "Brouillon de message",
    name: "Nom",
    phone: "Téléphone",
    email: "Email",
    faultAndService: "Panne & Service",
    serviceType: "Type de service",
    repairType: "Type de réparation",
    faultLevel: "Niveau de panne",
    appearance: "Apparence",
    faultDescription: "Description de la panne",
    remarks: "Remarques",
    addPart: "Ajouter pièce",
    part: "Pièce",
    quantity: "Quantité",
    price: "Prix",
    noPartsAdded: "Aucune pièce ajoutée.",
    attachments: "Pièces jointes",
    uploadFile: "Télécharger fichier",
    noAttachments: "Aucune pièce jointe.",
    save: "Enregistrer",
    saving: "Enregistrement...",
    adding: "Ajout...",
    // Customers page
    addCustomer: "Ajouter client",
    searchCustomers: "Rechercher clients...",
    noCustomersFound: "Aucun client trouvé",
    // Spare Parts page
    searchParts: "Rechercher pièces...",
    stock: "Stock",
    unitPrice: "Prix unitaire",
    partNumber: "Numéro de pièce",
    noPartsFound: "Aucune pièce trouvée",
    lowStock: "Stock faible",
  },
  ar: {
    workOrders: "أوامر العمل",
    spareParts: "قطع الغيار",
    customers: "العملاء",
    warranties: "الضمانات",
    satisfaction: "الرضا",
    csvImport: "استيراد CSV",
    analytics: "التحليلات",
    engineers: "المهندسون",
    reports: "التقارير",
    templates: "القوالب",
    shops: "المتاجر",
    expenses: "المصاريف",
    settings: "الإعدادات",
    appointments: "المواعيد",
    suppliers: "الموردون",
    certification: "الشهادة",
    messages: "الرسائل",
    pricing: "التسعير",
    contracts: "العقود",
    branches: "الفروع",
    pointOfSale: "نقطة البيع",
    shifts: "الورديات",
    academy: "الأكاديمية",
    notifications: "الإشعارات",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الداكن",
    installApp: "تثبيت التطبيق",
    logout: "تسجيل الخروج",
    orders: "الطلبات",
    parts: "القطع",
    markAllRead: "تحديد الكل كمقروء",
    noNotifications: "لا توجد إشعارات",
    sessionExpiring: "انتهاء الجلسة قريباً",
    sessionWarningBody: "سيتم تسجيل خروجك خلال {time} بسبب عدم النشاط.",
    stayLoggedIn: "البقاء متصلاً",
    // Dashboard / Work Orders list
    newWorkOrder: "أمر جديد",
    searchWorkOrders: "البحث بالعميل، الهاتف، الجهاز...",
    all: "الكل",
    noContact3d: "بلا تواصل 3 أيام+",
    allBranches: "كل الفروع",
    totalOrders: "إجمالي الأوامر",
    received: "مستلم",
    inProgress: "قيد التنفيذ",
    ready: "جاهز",
    revenue: "الإيرادات",
    delivered: "تم التسليم",
    cancelled: "ملغى",
    todaysAppointments: "مواعيد اليوم",
    noAppointmentsToday: "لا مواعيد اليوم",
    recentActivity: "النشاط الأخير",
    noRecentActivity: "لا نشاط حديث",
    viewAll: "عرض الكل",
    noOrdersMatchSearch: "لا توجد أوامر تطابق بحثك",
    noWorkOrdersYet: "لا توجد أوامر عمل بعد",
    tryDifferentSearch: "جرب بحثاً أو فلتراً مختلفاً",
    createFirstWorkOrder: "أنشئ أمر عملك الأول للبدء",
    selectAll: "تحديد الكل",
    selected: "محدد",
    changeStatus: "تغيير الحالة...",
    apply: "تطبيق",
    assignEngineer: "تعيين تقني...",
    assign: "تعيين",
    exportBtn: "تصدير",
    deleteBtn: "حذف",
    columns: "الأعمدة",
    orderHash: "رقم الأمر",
    customer: "العميل",
    device: "الجهاز",
    fault: "العطل",
    status: "الحالة",
    assignedTo: "مُعيَّن لـ",
    total: "المجموع",
    date: "التاريخ",
    view: "عرض",
    prev: "السابق",
    next: "التالي",
    page: "صفحة",
    showing: "عرض",
    deleteWorkOrders: "حذف أوامر العمل",
    cannotBeUndone: "لا يمكن التراجع عن هذا.",
    cancel: "إلغاء",
    deleting: "جارٍ الحذف...",
    morningBriefing: "إحاطة الصباح",
    justNow: "الآن",
    mAgo: "د",
    hAgo: "س",
    dAgo: "ي",
    // Work Order detail
    back: "رجوع",
    print: "طباعة",
    share: "مشاركة",
    whatsapp: "واتساب",
    sendReminder: "إرسال تذكير",
    healthReport: "تقرير الصحة",
    edit: "تعديل",
    reportBounce: "الإبلاغ عن عودة",
    startDiagnosis: "بدء التشخيص",
    startRepair: "بدء الإصلاح",
    markDone: "تحديد كمنتهٍ",
    markDelivered: "تحديد كمسلَّم",
    deviceInformation: "معلومات الجهاز",
    brand: "الماركة",
    model: "الموديل",
    serialNumber: "الرقم التسلسلي",
    imei: "الرقم التعريفي",
    warrantyStart: "بداية الضمان",
    warrantyEnd: "نهاية الضمان",
    customerInformation: "معلومات العميل",
    draftMessage: "صياغة رسالة",
    name: "الاسم",
    phone: "الهاتف",
    email: "البريد الإلكتروني",
    faultAndService: "العطل والخدمة",
    serviceType: "نوع الخدمة",
    repairType: "نوع الإصلاح",
    faultLevel: "مستوى العطل",
    appearance: "المظهر",
    faultDescription: "وصف العطل",
    remarks: "ملاحظات",
    addPart: "إضافة قطعة",
    part: "القطعة",
    quantity: "الكمية",
    price: "السعر",
    noPartsAdded: "لم تُضَف أي قطع بعد.",
    attachments: "المرفقات",
    uploadFile: "رفع ملف",
    noAttachments: "لا توجد مرفقات بعد.",
    save: "حفظ",
    saving: "جارٍ الحفظ...",
    adding: "جارٍ الإضافة...",
    // Customers page
    addCustomer: "إضافة عميل",
    searchCustomers: "البحث عن العملاء...",
    noCustomersFound: "لا عملاء",
    // Spare Parts page
    searchParts: "البحث عن قطع الغيار...",
    stock: "المخزون",
    unitPrice: "سعر الوحدة",
    partNumber: "رقم القطعة",
    noPartsFound: "لا قطع غيار",
    lowStock: "مخزون منخفض",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

type LanguageContextType = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKey) => string;
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key) => translations.en[key],
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  // Hydrate from localStorage on mount
  useEffect(() => {
    const stored = localStorage.getItem("lang") as Lang | null;
    if (stored && stored in translations) setLangState(stored);
  }, []);

  // Keep <html dir> and <html lang> in sync
  useEffect(() => {
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang]);

  function setLang(l: Lang) {
    setLangState(l);
    localStorage.setItem("lang", l);
  }

  function t(key: TranslationKey): string {
    return (translations[lang] as Record<string, string>)[key] ?? translations.en[key];
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
