"use client";

import { createContext, useContext, useEffect, useState } from "react";

export type Lang = "en" | "fr" | "ar";

export const translations = {
  en: {
    // Nav
    workOrders: "Work Orders",
    spareParts: "Spare Parts",
    customers: "Customers",
    warranties: "Warranties",
    satisfaction: "Satisfaction",
    csvImport: "CSV Import",
    analytics: "Analytics",
    engineers: "Engineers",
    reports: "Reports",
    templates: "Templates",
    shops: "Shops",
    expenses: "Expenses",
    settings: "Settings",
    appointments: "Appointments",
    suppliers: "Suppliers",
    certification: "Certification",
    messages: "Messages",
    pricing: "Pricing",
    contracts: "Contracts",
    branches: "Branches",
    pointOfSale: "Point of Sale",
    shifts: "Shifts",
    academy: "Academy",
    // Sidebar actions
    notifications: "Notifications",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    installApp: "Install App",
    logout: "Log out",
    // Bottom nav
    orders: "Orders",
    parts: "Parts",
    // Notifications panel
    markAllRead: "Mark all read",
    noNotifications: "No notifications",
    // Session warning
    sessionExpiring: "Session expiring soon",
    sessionWarningBody: "You'll be signed out in {time} due to inactivity.",
    stayLoggedIn: "Stay logged in",
    // Dashboard / Work Orders list
    newWorkOrder: "New Work Order",
    searchWorkOrders: "Search by customer, phone, device, order #...",
    all: "All",
    noContact3d: "No contact 3d+",
    allBranches: "All Branches",
    totalOrders: "Total Orders",
    received: "Received",
    inProgress: "In Progress",
    ready: "Ready",
    revenue: "Revenue",
    delivered: "Delivered",
    cancelled: "Cancelled",
    todaysAppointments: "Today's Appointments",
    noAppointmentsToday: "No appointments today",
    recentActivity: "Recent Activity",
    noRecentActivity: "No recent activity",
    viewAll: "View all",
    noOrdersMatchSearch: "No orders match your search",
    noWorkOrdersYet: "No work orders yet",
    tryDifferentSearch: "Try a different search or filter",
    createFirstWorkOrder: "Create your first work order to get started",
    selectAll: "Select all",
    selected: "selected",
    changeStatus: "Change status...",
    apply: "Apply",
    assignEngineer: "Assign engineer...",
    assign: "Assign",
    exportBtn: "Export",
    deleteBtn: "Delete",
    columns: "Columns",
    orderHash: "Order #",
    customer: "Customer",
    device: "Device",
    fault: "Fault",
    status: "Status",
    assignedTo: "Assigned To",
    total: "Total",
    date: "Date",
    view: "View",
    prev: "Prev",
    next: "Next",
    page: "Page",
    showing: "Showing",
    deleteWorkOrders: "Delete work orders",
    cannotBeUndone: "This cannot be undone.",
    cancel: "Cancel",
    deleting: "Deleting...",
    morningBriefing: "Morning Briefing",
    justNow: "just now",
    mAgo: "m ago",
    hAgo: "h ago",
    dAgo: "d ago",
    // Work Order detail
    back: "Back",
    print: "Print",
    share: "Share",
    whatsapp: "WhatsApp",
    sendReminder: "Send Reminder",
    healthReport: "Health Report",
    edit: "Edit",
    reportBounce: "Report Bounce",
    startDiagnosis: "Start Diagnosis",
    startRepair: "Start Repair",
    markDone: "Mark Done",
    markDelivered: "Mark Delivered",
    deviceInformation: "Device Information",
    brand: "Brand",
    model: "Model",
    serialNumber: "Serial Number",
    imei: "IMEI",
    warrantyStart: "Warranty Start",
    warrantyEnd: "Warranty End",
    customerInformation: "Customer Information",
    draftMessage: "Draft Message",
    name: "Name",
    phone: "Phone",
    email: "Email",
    faultAndService: "Fault & Service",
    serviceType: "Service Type",
    repairType: "Repair Type",
    faultLevel: "Fault Level",
    appearance: "Appearance",
    faultDescription: "Fault Description",
    remarks: "Remarks",
    addPart: "Add Part",
    part: "Part",
    quantity: "Quantity",
    price: "Price",
    noPartsAdded: "No parts added yet.",
    attachments: "Attachments",
    uploadFile: "Upload File",
    noAttachments: "No attachments yet.",
    save: "Save",
    saving: "Saving...",
    adding: "Adding...",
    // Customers page
    addCustomer: "Add Customer",
    searchCustomers: "Search customers...",
    noCustomersFound: "No customers found",
    // Spare Parts page
    searchParts: "Search parts...",
    stock: "Stock",
    unitPrice: "Unit Price",
    partNumber: "Part Number",
    noPartsFound: "No parts found",
    lowStock: "Low stock",
    // Analytics page
    analyticsSubtitle: "Revenue, expenses, profit and insights",
    days7: "7 days",
    days30: "30 days",
    days90: "90 days",
    allTime: "All time",
    analyticsCSV: "Analytics CSV",
    tabOverview: "Overview",
    tabBenchmarks: "Benchmarks",
    tabCopilot: "Copilot",
    kpiTotalOrders: "Total Orders",
    kpiCollected: "Collected",
    kpiExpenses: "Expenses",
    kpiNetProfit: "Net Profit",
    kpiOutstanding: "Outstanding",
    kpiActive: "active",
    kpiRate: "rate",
    kpiMargin: "margin",
    kpiUnpaid: "unpaid",
    kpiTotalCosts: "Total costs",
    momTitle: "Month-over-Month",
    collectionRate: "Collection Rate",
    revenueExpensesProfit: "Revenue, Expenses & Profit",
    revenueExpensesSubtitle: "Billed vs collected vs expenses vs net profit",
    noDataYet: "No data yet.",
    workOrdersVolume: "Work Orders Volume",
    ordersPerPeriod: "Number of orders per period",
    ordersByStatus: "Orders by Status",
    currentDistribution: "Current distribution",
    noData: "No data.",
    engineerLeaderboard: "Engineer Leaderboard",
    engineerLeaderboardSubtitle: "Performance ranked by completed orders",
    noEngineersYet: "No engineers yet.",
    topSparePartsUsed: "Top Spare Parts Used",
    topPartsSubtitle: "Most used parts this period",
    noPartsDataYet: "No parts data yet.",
    stockStatus: "Stock Status",
    partsBelowFive: "Parts below 5 units",
    allPartsWellStocked: "All parts well stocked",
    slaCompliance: "SLA Compliance",
    slaSubtitle: "Orders completed within their deadline",
    noSlaOrders: "No completed orders with SLA deadlines yet.",
    slaMetLabel: "Met SLA",
    slaBreachedLabel: "Breached",
    referralSources: "Referral Sources",
    howCustomersFind: "How customers find you",
    loyaltyMilestones: "Loyalty Milestones",
    loyaltySubtitle: "Customer engagement highlights",
    anniversariesThisMonth: "Anniversaries this month",
    tenPlusCustomers: "10+ order customers",
    goldVip: "Gold VIP (6+ orders)",
    somethingWentWrong: "Something went wrong",
    tryAgain: "Try again",
    loadingAnalysis: "Analyzing 90 days of revenue data…",
    generateAnalysis: "Generate Analysis",
    revenueCopilot: "Revenue Copilot",
    copilotDescription: "90-day business intelligence report",
    // Appointments page
    todaysCheckins: "Today's Check-ins",
    allAppointments: "All Appointments",
    calendarView: "Calendar",
    listView: "List",
    checkinsView: "Check-ins",
    newAppointment: "New Appointment",
    appointmentDetails: "Appointment Details",
    editAppointment: "Edit Appointment",
    newAppointmentTitle: "New Appointment",
    customerName: "Customer Name",
    dateAndTime: "Date & Time",
    issueLabel: "Issue",
    duration: "Duration",
    createAppointment: "Create Appointment",
    creating: "Creating…",
    noAppointmentsStatus: "No appointments with this status",
    noAppointmentsYet: "No appointments yet",
    dateTimeHeader: "Date & Time",
    actionsHeader: "Actions",
    confirmAction: "Confirm",
    cancelAction: "Cancel",
    reschedule: "Reschedule",
    newDateTime: "New date & time",
    confirmReschedule: "Confirm Reschedule",
    savingLabel: "Saving…",
    saveChanges: "Save Changes",
    sendWhatsApp: "Send WhatsApp Confirmation",
    convertToWorkOrder: "Convert to Work Order",
    bookedOn: "Booked",
    minAppointment: "min appointment",
    liveRefreshes: "Live · refreshes every 30s",
    updating: "updating…",
    refreshBtn: "Refresh",
    qrCode: "QR Code",
    appointmentsCheckedIn: "Appointments Checked In",
    walkInsLabel: "Walk-ins",
    totalCheckins: "Total",
    noCheckinsToday: "No check-ins today yet",
    shareQrCode: "Share the QR code with customers to start receiving check-ins",
    showQrCode: "Show QR Code",
    customerCheckinQr: "Customer Check-in QR",
    copyLink: "Copy Link",
    createWorkOrderModal: "Create Work Order",
    deviceBrandLabel: "Device Brand",
    deviceModelLabel: "Device Model",
    workOrderCreated: "✓ Work order created",
    // Reports page
    reportsSubtitle: "Monthly revenue, expenses, and profit summary",
    exportPdf: "Export PDF",
    loadingReport: "Loading report...",
    yearlySummary: "Summary",
    collectedLabel: "Collected",
    outstandingLabel: "Outstanding",
    uncollected: "uncollected",
    totalCosts: "total costs",
    ordersLabel: "Orders",
    monthByMonth: "Month-by-Month Breakdown",
    monthLabel: "Month",
    collRate: "Coll. Rate",
    netProfit: "Net Profit",
    noDataForYear: "No data for",
    totalRow: "Total",
    referralSourcesTitle: "Referral Sources",
    referralSubtitle: "Which channels bring the most customers and revenue.",
    fromLabel: "From",
    toLabel: "To",
    applyBtn: "Apply",
    clearBtn: "Clear",
    loadingLabel: "Loading...",
    noReferralData: "No referral source data yet. Start selecting a source when creating work orders.",
    sourceHeader: "Source",
    ordersHeader: "Orders",
    shareHeader: "Share",
    revenueHeader: "Revenue",
    avgOrderHeader: "Avg Order",
    accountingExport: "Accounting Export",
    accountingSubtitle: "Export payments, expenses, and commissions for your accounting software. Includes tax breakdown per transaction.",
    thisMonthLabel: "This month",
    thisYearLabel: "This year",
    lastYearLabel: "Last year",
    preparingLabel: "Preparing…",
    partsReport: "Parts Report",
    totalPartsUsed: "Total Parts Used",
    partsRevenue: "Parts Revenue",
    partsConsumption: "Parts Consumption",
    noPartsThisPeriod: "No data for this period.",
    timesUsed: "Times Used",
    stockAdjustmentHistory: "Stock Adjustment History",
    noAdjustments: "No adjustments recorded.",
    typeHeader: "Type",
    qtyHeader: "Qty",
    reasonHeader: "Reason",
    byHeader: "By",
    // Suppliers page
    suppliersSubtitle: "Manage suppliers and purchase orders",
    addSupplier: "Add Supplier",
    newSupplier: "New Supplier",
    saveSupplier: "Save Supplier",
    noSuppliersYet: "No suppliers yet",
    addFirstSupplier: "Add your first supplier to start creating purchase orders.",
    searchSuppliers: "Search suppliers by name, phone or email...",
    purchaseOrders: "Purchase Orders",
    noPurchaseOrders: "No purchase orders",
    createPoFromTab: "Create a purchase order from the Suppliers tab.",
    newPurchaseOrder: "New Purchase Order",
    viewOrders: "View Orders",
    selectPart: "Select part...",
    addAnotherPart: "+ Add another part",
    notesOptional: "Notes (optional)",
    createDraftPo: "Create Draft PO",
    editPurchaseOrder: "Edit Purchase Order",
    markSent: "Mark Sent",
    markReceived: "Mark Received",
    allSuppliersOption: "All Suppliers",
    // POS page
    posTitle: "Point of Sale",
    ordersReadyPickup: "orders ready for pickup",
    noOrdersWaiting: "No orders waiting",
    allDelivered: "All done orders have been delivered",
    checkoutTitle: "Checkout",
    orderTotal: "Order total",
    alreadyCollected: "Already collected",
    balanceDue: "Balance due",
    paymentMethod: "Payment method",
    customerPays: "Customer pays",
    changeToGive: "Change to give back",
    noChangeDue: "No change due",
    orderFullyPaid: "Order fully paid ✓",
    tapDeliver: "Tap Deliver below to complete handoff",
    markAsDelivered: "✓ Mark as Delivered",
    printReceipt: "Print Receipt",
    selectAnOrder: "Select an order",
    tapDoneOrder: "Tap a DONE order to check out the customer",
    todayLabel: "Today",
    // Expenses page
    expensesSubtitle: "Track your shop expenses",
    exportCsv: "Export CSV",
    addExpense: "Add Expense",
    totalExpenses: "Total Expenses",
    newExpense: "New Expense",
    titleLabel: "Title",
    amountLabel: "Amount",
    categoryLabel: "Category",
    noteLabel: "Note",
    saveExpense: "Save Expense",
    searchExpensesByTitle: "Search by title or note...",
    noMatchingExpenses: "No matching expenses",
    noExpensesYet: "No expenses yet",
    noExpensesDesc: "Track rent, salaries, supplies and more to get a clear picture of your shop's costs.",
    addFirstExpense: "+ Add First Expense",
    // Shifts page
    shiftsSubtitle: "Track work hours across all staff",
    shiftsSubtitleOwn: "Track your work hours",
    currentlyWorking: "Currently working",
    clockOut: "Clock Out",
    notClockedIn: "Not clocked in",
    clockIn: "Clock In",
    clockingIn: "Clocking in…",
    thisWeek: "This Week",
    shiftsHistory: "History",
    shiftsTotal: "shifts total",
    noShiftsYet: "No shifts recorded yet",
    clockInToStart: "Clock in above to start tracking hours",
    engineerHeader: "Engineer",
    clockInHeader: "Clock In",
    clockOutHeader: "Clock Out",
    durationHeader: "Duration",
    notesHeader: "Notes",
    activeStatus: "Active",
    // New Work Order page
    newWorkOrderTitle: "New Work Order",
    hideTemplates: "Hide Templates",
    useTemplate: "Use Template",
    templateApplied: "Template applied",
    step1DeviceInfo: "Device Info",
    step2Customer: "Customer",
    step3FaultPhotos: "Fault & Photos",
    fillRequiredFields: "Please fill in all required fields.",
    devicePhotos: "Device Photos",
    devicePhotosDesc: "Document device condition on intake — protects against disputes",
    addPhotos: "Add Photos",
    clickToAddPhotos: "Click to add device photos",
    photoFrontBack: "Front, back, sides, any existing damage",
    photoRequired: "⚠ Device photo is required",
    atLeastOnePhoto: "At least one device photo is required",
    addMore: "Add more",
    returningCustomer: "👤 Returning Customer",
    useThisCustomer: "Use this customer",
    totalOrdersLabel: "Total Orders",
    lastVisitLabel: "Last Visit",
    faultService: "Fault & Service",
    faultDescriptionLabel: "Fault Description *",
    describeFault: "Describe the fault...",
    aiRepairEstimate: "AI Repair Estimate",
    estDuration: "Est. Duration",
    costRange: "Cost Range",
    likelyParts: "Likely Parts",
    noneExpected: "None expected",
    successRate: "Success Rate",
    aiDisclaimer: "AI estimates are indicative only and may vary based on actual device condition.",
    appearanceLabel: "Appearance",
    repairTypeLabel: "Repair Type",
    serviceTypeLabel: "Service Type",
    faultLevelLabel: "Fault Level",
    branchLabel: "Branch",
    noBranch: "— No Branch —",
    howDidTheyFind: "How did they find us?",
    selectSource: "— Select source —",
    referredBy: "Referred by (customer name)",
    remarksLabel: "Remarks",
    additionalRemarks: "Any additional remarks...",
    createWorkOrderBtn: "Create Work Order",
    // Edit Work Order page
    editWorkOrderTitle: "Edit Work Order",
    adminOnly: "(Admin only)",
    underWarranty: "Under warranty",
    failedToSave: "Failed to save",
    deviceIsUnderWarranty: "Device is under warranty",

    // ── Branches page ──────────────────────────────────────────
    manageBranchesSubtitle: "Manage multiple locations under one shop",
    addBranch: "Add Branch",
    totalBranches: "Total Branches",
    active: "Active",
    totalStaff: "Total Staff",
    newBranch: "New Branch",
    branchName: "Branch Name",
    address: "Address",
    branchManager: "Branch Manager",
    noneOption: "— None —",
    createBranch: "Create Branch",
    loading: "Loading…",
    noBranchesYet: "No branches yet",
    createFirstBranch: "Create your first branch to manage multiple locations",
    staff: "Staff",
    workOrdersCount: "Work Orders",
    partsCount: "Parts",
    editBranch: "Edit Branch",
    manager: "Manager",
    deleteBranch: "Delete Branch?",
    deleteBranchWarning: "Work orders, engineers, and parts linked to this branch will be unassigned but not deleted.",
    deleteBranchConfirm: "Delete Branch",
    assignEngineersLabel: "Assign Engineers",
    noEngineersFound: "No engineers found",
    engineerUnassigned: "Engineer unassigned",
    engineerAssigned: "Engineer assigned",
    branchCreated: "Branch created",
    branchUpdated: "Branch updated",
    branchDeleted: "Branch deleted",

    // ── Certification page ──────────────────────────────────────
    shopCertification: "Shop Certification",
    certSubtitle: "Automatically awarded based on repairs, ratings, and quality.",
    couldNotLoadCert: "Could not load certification data.",
    noCertYet: "No certification yet",
    noCertDesc: "Complete 10+ repairs with a 3.5+ avg rating to earn Bronze.",
    downloadBadge: "Download Badge",
    earnedDate: "Earned",
    activeCertification: "Active certification",
    workToward: "Work toward",
    certNext: "next",
    completedRepairs: "Completed Repairs",
    avgRating: "Avg Rating",
    bounceRate: "Bounce Rate",
    nextGoal: "Next goal",
    achieved: "✓ Achieved",
    completedRepairsLabel: "Completed repairs",
    avgRatingLabel: "Avg rating",
    bounceRateLower: "Bounce rate (lower is better)",
    certAutoCalc: "Certifications are calculated automatically every time a work order is marked as",
    certFree: "All certifications are free and permanent as long as your shop meets the criteria.",

    // ── Contracts page ──────────────────────────────────────────
    maintenanceContracts: "Maintenance Contracts",
    contractsSubtitle: "Recurring service agreements with automatic work order generation",
    newContract: "New Contract",
    activeContracts: "Active Contracts",
    monthlyRevenue: "Monthly Revenue",
    annualRevenue: "Annual Revenue",
    dueForBilling: "Due for Billing",
    loadingContracts: "Loading contracts…",
    noContractsYet: "contracts yet",
    createContractHint: "Create a contract to start tracking recurring maintenance revenue",
    customerPhone: "Customer Phone",
    deviceBrand: "Device Brand",
    deviceModel: "Device Model",
    serviceDescription: "Service Description",
    monthlyPrice: "Monthly Price",
    startDate: "Start Date",
    endDate: "End Date (optional)",
    notes: "Notes",
    internalNotes: "Internal notes",
    createContract: "Create Contract",
    editContract: "Edit Contract",
    contractStatus: "Status",
    pause: "Pause",
    resume: "Resume",
    dismiss: "Dismiss",
    billedBanner: "billed — work orders created automatically.",
    nextBilling: "Next:",
    endsOn: "Ends",

    // ── CSV page ───────────────────────────────────────────────
    csvImportTitle: "CSV Import",
    csvImportSubtitle: "Bulk import spare parts or customers from a spreadsheet",
    whatAreYouImporting: "What are you importing?",
    needTemplate: "Need a template?",
    downloadTemplate: "Download",
    uploadCsvFile: "Upload CSV file",
    dropCsvHere: "Drop your CSV here, or click to browse",
    csvFilesOnly: ".csv files only",
    clickToChange: "KB · Click to change",
    nextMapColumns: "Next: Map Columns →",
    mapColumns: "Map columns",
    mapColumnsHint: "Match your CSV columns to the expected fields. Auto-mapped where possible.",
    rowsDetected: "rows detected",
    fieldCol: "Field",
    csvColumn: "CSV Column",
    sampleValue: "Sample value",
    requiredField: "required",
    skipOption: "— skip —",
    preview: "Preview",
    firstRows: "first",
    ofLabel: "of",
    rowsLabel: "rows",
    readyLabel: "ready",
    willBeSkipped: "will be skipped",
    importingLabel: "Importing…",
    importRows: "Import",
    importAnotherFile: "Import another file",
    totalRowsLabel: "Total rows",
    importedLabel: "Imported",
    skippedLabel: "Skipped",
    allRowsImported: "All rows imported successfully!",
    errorsLabel: "Errors",
    rowsSkipped: "rows skipped",
    downloadErrorReport: "⬇ Download error report",
    rowCol: "Row",
    reasonLabel: "Reason",
    dataLabel: "Data",

    // ── Customer detail page ────────────────────────────────────
    repeatCustomer: "Repeat Customer",
    customerInfo: "Customer Info",
    summary: "Summary",
    totalSpent: "Total Spent",
    collectedLabel2: "Collected",
    outstanding2: "Outstanding",
    teamNotes: "Team Notes",
    internalOnly: "Internal only",
    addNoteHint: "Add a note about this customer... (Ctrl+Enter to save)",
    addNote: "Add Note",
    noNotesYet: "No notes yet. Add one above.",
    repairHistory: "Repair History",
    noOrdersFound: "No orders found.",
    snCol: "SN",
    partsCol: "Parts",

    // ── Engineers / Commissions page ────────────────────────────
    engineerCommissions: "Engineer Commissions",
    commissionsSubtitle: "Monthly commission tracking per engineer",
    totalRevenue: "Total Revenue",
    totalCommissions: "Total Commissions",
    saveSnapshot: "💾 Save Snapshot",
    engineerCol: "Engineer",
    roleCol: "Role",
    ordersCol: "Orders",
    revenueCol: "Revenue",
    commissionRate: "Commission Rate",
    commissionAmount: "Commission Amount",
    lockedCol: "Locked?",
    noEngineersFoundComm: "No engineers found.",
    commissionSaved: "Commission snapshot saved.",
    commissionFailed: "Failed to save.",
    commissionFormula: "Commission is calculated as:",
    commissionFormulaDetail: "for orders with status DONE or DELIVERED, updated in",
    useSnapshotHint: "Use \"Save Snapshot\" to lock the current figures.",
    savedLabel: "Saved",

    // ── Engineers page ─────────────────────────────────────────
    teamPerformance: "Team performance overview",
    commissionsLink: "💸 Commissions",
    addEngineer: "Add Engineer",
    newEngineer: "New Engineer",
    fullName: "Full name",
    temporaryPassword: "Temporary password",
    noTeamMembersYet: "No team members yet",
    addEngineersHint: "Add engineers to your shop so they can log in and work on orders.",
    totalRevenueStat: "Total Revenue",
    commissionStat: "Commission",
    assigned: "Assigned",
    completed: "Completed",
    deliveredStat: "Delivered",
    cancelledStat: "Cancelled",
    bounces: "Bounces",
    avgTat: "Avg TAT",
    completionRate: "Completion rate",
    newPassword: "New Password",
    leaveBlank: "leave blank to keep",
    commissionRatePct: "Commission Rate (%)",
    failedToLoad: "Failed to load",
    allFieldsRequired: "All fields are required",

    // ── Messages page ──────────────────────────────────────────
    messagesTitle: "Messages",
    messagesSubtitle: "Customer conversations across all work orders",
    noMessagesYet: "No messages yet.",
    messagesWillAppear: "Messages from customers will appear here.",
    customerLabel: "Customer:",
    youLabel: "You:",

    // ── Pricing page ───────────────────────────────────────────
    pricingEngine: "Pricing Engine",
    pricingSubtitle: "Track, analyze, and optimize your repair pricing",
    addHistoricalPrice: "+ Add Historical Price",
    addHistoricalPricingEntry: "Add Historical Pricing Entry",
    priceCharged: "Price Charged",
    partsCost: "Parts Cost",
    customerAccepted: "Customer Accepted?",
    yesOption: "Yes",
    noRejected: "No (rejected / walked away)",
    saveEntry: "Save Entry",
    repairTypesTracked: "Repair Types Tracked",
    totalEntries: "Total Entries",
    mostDone: "Most Done",
    underpricedRepairs: "Underpriced Repairs",
    allRepairTypes: "All Repair Types",
    analyticsTab: "Analytics",
    searchRepairType: "Search repair type…",
    typesLabel: "types",
    noPricingDataYet: "No pricing data yet.",
    pricingAutoSaved: "Prices are saved automatically when work orders are delivered, or add them manually above.",
    minLabel: "Min",
    averageLabel: "Average",
    maxLabel: "Max",
    marginLabel: "Margin",
    mostProfitable: "Most Profitable Repairs",
    leastProfitable: "Least Profitable — Consider Raising Prices",
    leastProfitableHint: "Repairs where your margin is lowest. Consider raising prices or reducing parts cost.",
    underpricedTitle: "Underpriced Repairs",
    underpricedHint: "These repairs have under 20% margin — you may be losing money after parts + labor.",
    raiseTitle: "Opportunity — Consider Raising Prices",
    raiseHint: "These repairs have ≥90% customer acceptance rate — the market can bear a higher price.",
    dropTitle: "Low Acceptance — Review or Drop",
    dropHint: "Low acceptance rate means customers are rejecting quotes. Consider lowering price or discontinuing.",
    notEnoughData: "Not enough data yet.",
    notEnoughDataFull: "Not enough data yet",
    notEnoughDataDesc: "Deliver more work orders or add historical entries to unlock pricing analytics.",

    // ── Ratings page ──────────────────────────────────────────
    customerSatisfaction: "Customer Satisfaction",
    ratingsSubtitle: "Ratings collected after delivery",
    reviewsLabel: "reviews",
    noRatingsYet: "No ratings yet",
    ratingsWillAppear: "Customer ratings appear here after work orders are marked as delivered.",
    failedLoadRatings: "Failed to load ratings",

    // ── Shops page ────────────────────────────────────────────
    shopManagement: "Shop Management",
    shopManagementSubtitle: "Manage your shop settings and all tenant shops",
    myShopSettings: "My Shop Settings",
    shopName: "Shop Name",
    savedSuccessfully: "✓ Saved successfully",
    allTenantShops: "All Tenant Shops",
    shopCol: "Shop",
    ownerCol: "Owner",
    ordersShopCol: "Orders",
    planCol: "Plan",
    trialEnds: "Trial Ends",
    actionsCol: "Actions",
    noShopsYet: "No shops yet.",
    activate: "Activate",
    trialBtn: "Trial",
    suspendBtn: "Suspend",
    superAdminRequired: "Super admin access required.",
    trialDaysLeft: "Trial:",
    daysLeft: "days left",
    sinceLabel: "Since",

    // ── Templates page ────────────────────────────────────────
    workOrderTemplates: "Work Order Templates",
    templatesSubtitle: "Pre-fill common repairs to save time",
    newTemplate: "New Template",
    templateName: "Template Name",
    categoryLabel2: "Category",
    noCategory: "No category",
    estimatedDuration: "Estimated Duration",
    minutes: "minutes",
    defaultPrice: "Default Price",
    defaultSpareParts: "Default Spare Parts",
    defaultLineItems: "Default Line Items (Labor, Services)",
    laborFeeHint: "e.g. Labor fee",
    saveTemplate: "Save Template",
    noTemplatesYet: "No templates yet",
    noTemplatesDesc: "Templates let you pre-fill common repairs — brand, fault, parts, and pricing in one click.",
    createFirstTemplate: "+ Create First Template",
    noTemplatesInCategory: "No templates in",
    tryClearFilter: "Try a different category or clear the filter.",
    deleteTemplateConfirm: "Delete this template?",

    // ── Warranties page ───────────────────────────────────────
    warrantiesTitle: "Warranties",
    warrantiesSubtitle: "Track warranty status across all repaired devices",
    underWarrantyLabel: "under warranty",
    expiringSoon: "Expiring Soon",
    within30Days: "within 30 days",
    expiredLabel: "Expired",
    pastEndDate: "past end date",
    tabActive: "Active",
    tabExpiringSoon: "Expiring Soon",
    tabExpired: "Expired",
    noActiveWarranties: "No active warranties",
    noActiveWarrantiesDesc: "Warranties appear here once a work order has a warranty end date set.",
    nothingExpiringSoon: "Nothing expiring soon",
    nothingExpiringSoonDesc: "You're all clear — no warranties expiring within the next 30 days.",
    noExpiredWarranties: "No expired warranties",
    noExpiredWarrantiesDesc: "Expired warranties will show up here once they pass their end date.",
    warrantyPeriod: "Warranty Period",
    remainingLabel: "Remaining",
    unassigned: "Unassigned",
    warrantyEnds: "Warranty ends",
    startedLabel: "Started",
    repairedLabel: "Repaired",

    // ── Academy page ──────────────────────────────────────────
    academyTitle: "🎓 FixFlow Academy",
    academySubtitle: "Free courses to help you master your repair shop",
    enrolledLabel: "Enrolled",
    completedCourses: "Completed",
    lessonsCount: "lessons",
    courseContent: "Course Content",
    enrollFree: "Enroll for Free & Start Learning",
    enrolling: "Enrolling…",
    reviewCourse: "Review Course",
    continueCourse: "Continue →",
    startLearning: "Start Learning →",
    certificateEarned: "Certificate earned · View",
    certOfCompletion: "Certificate of Completion earned",
    viewCertificate: "View certificate →",
    backToCourse: "Back to course →",
    markComplete: "Mark Complete",
    markCompleteSaving: "Saving…",
    markCompleteFinish: "Mark Complete & Finish →",
    courseNotFound: "Course not found",
    lessonNotFound: "Lesson not found.",
    courseOutline: "Course Outline",
    totalMinutes: "minutes total",

    // ── Health Report page ────────────────────────────────────
    deviceHealthReport: "Device Health Report",
    postRepairAssessment: "Post-Repair Condition Assessment",
    failedLoadHealthReport: "⚠️ Failed to load health report",
    goBack: "Go back",
    orderNotFound: "Order not found",
    printSavePdf: "🖨 Print / Save PDF",
    repairSummary: "Repair Summary",
    issueReported: "Issue Reported",
    receivedLabel2: "Received",
    completedLabel: "Completed",
    technicianLabel: "Technician",
    partsReplaced: "Parts Replaced",
    deviceConditionAssessment: "Device Condition Assessment",
    issuesLabel: "Issues",
    discountLabel: "Discount",
    subtotalLabel: "Subtotal",
    taxLabel: "tax",
    totalInclTax: "Total incl. tax",
    healthReportFooter: "This health report certifies the device was repaired and tested by",
    generatedBy: "Generated by FixFlow ·",
  },
  fr: {
    workOrders: "Ordres de travail",
    spareParts: "Pièces détachées",
    customers: "Clients",
    warranties: "Garanties",
    satisfaction: "Satisfaction",
    csvImport: "Import CSV",
    analytics: "Analytique",
    engineers: "Techniciens",
    reports: "Rapports",
    templates: "Modèles",
    shops: "Boutiques",
    expenses: "Dépenses",
    settings: "Paramètres",
    appointments: "Rendez-vous",
    suppliers: "Fournisseurs",
    certification: "Certification",
    messages: "Messages",
    pricing: "Tarification",
    contracts: "Contrats",
    branches: "Succursales",
    pointOfSale: "Point de vente",
    shifts: "Quarts de travail",
    academy: "Académie",
    notifications: "Notifications",
    lightMode: "Mode clair",
    darkMode: "Mode sombre",
    installApp: "Installer",
    logout: "Déconnexion",
    orders: "Ordres",
    parts: "Pièces",
    markAllRead: "Tout marquer lu",
    noNotifications: "Aucune notification",
    sessionExpiring: "Session bientôt expirée",
    sessionWarningBody: "Vous serez déconnecté dans {time} en raison d'inactivité.",
    stayLoggedIn: "Rester connecté",
    // Dashboard / Work Orders list
    newWorkOrder: "Nouvel ordre",
    searchWorkOrders: "Rechercher par client, téléphone, appareil, n° ordre...",
    all: "Tout",
    noContact3d: "Sans contact 3j+",
    allBranches: "Toutes les succursales",
    totalOrders: "Total des ordres",
    received: "Reçu",
    inProgress: "En cours",
    ready: "Prêt",
    revenue: "Revenus",
    delivered: "Livré",
    cancelled: "Annulé",
    todaysAppointments: "Rendez-vous du jour",
    noAppointmentsToday: "Aucun rendez-vous aujourd'hui",
    recentActivity: "Activité récente",
    noRecentActivity: "Aucune activité récente",
    viewAll: "Voir tout",
    noOrdersMatchSearch: "Aucun ordre ne correspond à votre recherche",
    noWorkOrdersYet: "Aucun ordre de travail",
    tryDifferentSearch: "Essayez une autre recherche ou un autre filtre",
    createFirstWorkOrder: "Créez votre premier ordre pour commencer",
    selectAll: "Tout sélectionner",
    selected: "sélectionné(s)",
    changeStatus: "Changer le statut...",
    apply: "Appliquer",
    assignEngineer: "Assigner technicien...",
    assign: "Assigner",
    exportBtn: "Exporter",
    deleteBtn: "Supprimer",
    columns: "Colonnes",
    orderHash: "N° ordre",
    customer: "Client",
    device: "Appareil",
    fault: "Panne",
    status: "Statut",
    assignedTo: "Assigné à",
    total: "Total",
    date: "Date",
    view: "Voir",
    prev: "Préc.",
    next: "Suiv.",
    page: "Page",
    showing: "Affichage",
    deleteWorkOrders: "Supprimer les ordres",
    cannotBeUndone: "Cette action est irréversible.",
    cancel: "Annuler",
    deleting: "Suppression...",
    morningBriefing: "Briefing du matin",
    justNow: "à l'instant",
    mAgo: "min",
    hAgo: "h",
    dAgo: "j",
    // Work Order detail
    back: "Retour",
    print: "Imprimer",
    share: "Partager",
    whatsapp: "WhatsApp",
    sendReminder: "Envoyer rappel",
    healthReport: "Rapport de santé",
    edit: "Modifier",
    reportBounce: "Signaler retour",
    startDiagnosis: "Commencer diagnostic",
    startRepair: "Commencer réparation",
    markDone: "Marquer terminé",
    markDelivered: "Marquer livré",
    deviceInformation: "Informations appareil",
    brand: "Marque",
    model: "Modèle",
    serialNumber: "Numéro de série",
    imei: "IMEI",
    warrantyStart: "Début garantie",
    warrantyEnd: "Fin garantie",
    customerInformation: "Informations client",
    draftMessage: "Brouillon de message",
    name: "Nom",
    phone: "Téléphone",
    email: "Email",
    faultAndService: "Panne & Service",
    serviceType: "Type de service",
    repairType: "Type de réparation",
    faultLevel: "Niveau de panne",
    appearance: "Apparence",
    faultDescription: "Description de la panne",
    remarks: "Remarques",
    addPart: "Ajouter pièce",
    part: "Pièce",
    quantity: "Quantité",
    price: "Prix",
    noPartsAdded: "Aucune pièce ajoutée.",
    attachments: "Pièces jointes",
    uploadFile: "Télécharger fichier",
    noAttachments: "Aucune pièce jointe.",
    save: "Enregistrer",
    saving: "Enregistrement...",
    adding: "Ajout...",
    // Customers page
    addCustomer: "Ajouter client",
    searchCustomers: "Rechercher clients...",
    noCustomersFound: "Aucun client trouvé",
    // Spare Parts page
    searchParts: "Rechercher pièces...",
    stock: "Stock",
    unitPrice: "Prix unitaire",
    partNumber: "Numéro de pièce",
    noPartsFound: "Aucune pièce trouvée",
    lowStock: "Stock faible",
    // Analytics page
    analyticsSubtitle: "Revenus, dépenses, bénéfice et insights",
    days7: "7 jours",
    days30: "30 jours",
    days90: "90 jours",
    allTime: "Toute la période",
    analyticsCSV: "CSV Analytique",
    tabOverview: "Aperçu",
    tabBenchmarks: "Benchmarks",
    tabCopilot: "Copilote",
    kpiTotalOrders: "Total des ordres",
    kpiCollected: "Collecté",
    kpiExpenses: "Dépenses",
    kpiNetProfit: "Bénéfice net",
    kpiOutstanding: "Impayé",
    kpiActive: "actif",
    kpiRate: "taux",
    kpiMargin: "marge",
    kpiUnpaid: "impayé",
    kpiTotalCosts: "Coûts totaux",
    momTitle: "Mois sur mois",
    collectionRate: "Taux de collecte",
    revenueExpensesProfit: "Revenus, Dépenses & Bénéfice",
    revenueExpensesSubtitle: "Facturé vs collecté vs dépenses vs bénéfice net",
    noDataYet: "Aucune donnée.",
    workOrdersVolume: "Volume des ordres",
    ordersPerPeriod: "Nombre d'ordres par période",
    ordersByStatus: "Ordres par statut",
    currentDistribution: "Distribution actuelle",
    noData: "Aucune donnée.",
    engineerLeaderboard: "Classement des techniciens",
    engineerLeaderboardSubtitle: "Performance classée par ordres terminés",
    noEngineersYet: "Aucun technicien.",
    topSparePartsUsed: "Pièces les plus utilisées",
    topPartsSubtitle: "Pièces les plus utilisées cette période",
    noPartsDataYet: "Aucune donnée de pièces.",
    stockStatus: "État du stock",
    partsBelowFive: "Pièces en dessous de 5 unités",
    allPartsWellStocked: "Toutes les pièces bien approvisionnées",
    slaCompliance: "Conformité SLA",
    slaSubtitle: "Ordres terminés dans leur délai",
    noSlaOrders: "Aucun ordre terminé avec des délais SLA.",
    slaMetLabel: "SLA respecté",
    slaBreachedLabel: "Dépassé",
    referralSources: "Sources de référence",
    howCustomersFind: "Comment les clients vous trouvent",
    loyaltyMilestones: "Jalons de fidélité",
    loyaltySubtitle: "Points forts de l'engagement client",
    anniversariesThisMonth: "Anniversaires ce mois",
    tenPlusCustomers: "Clients 10+ ordres",
    goldVip: "VIP Or (6+ ordres)",
    somethingWentWrong: "Quelque chose s'est mal passé",
    tryAgain: "Réessayer",
    loadingAnalysis: "Analyse de 90 jours de données…",
    generateAnalysis: "Générer l'analyse",
    revenueCopilot: "Copilote revenus",
    copilotDescription: "Rapport de veille commerciale 90 jours",
    // Appointments page
    todaysCheckins: "Enregistrements du jour",
    allAppointments: "Tous les rendez-vous",
    calendarView: "Calendrier",
    listView: "Liste",
    checkinsView: "Enregistrements",
    newAppointment: "Nouveau rendez-vous",
    appointmentDetails: "Détails du rendez-vous",
    editAppointment: "Modifier rendez-vous",
    newAppointmentTitle: "Nouveau rendez-vous",
    customerName: "Nom du client",
    dateAndTime: "Date & Heure",
    issueLabel: "Problème",
    duration: "Durée",
    createAppointment: "Créer rendez-vous",
    creating: "Création…",
    noAppointmentsStatus: "Aucun rendez-vous avec ce statut",
    noAppointmentsYet: "Aucun rendez-vous",
    dateTimeHeader: "Date & Heure",
    actionsHeader: "Actions",
    confirmAction: "Confirmer",
    cancelAction: "Annuler",
    reschedule: "Reprogrammer",
    newDateTime: "Nouvelle date & heure",
    confirmReschedule: "Confirmer la reprogrammation",
    savingLabel: "Enregistrement…",
    saveChanges: "Enregistrer les modifications",
    sendWhatsApp: "Envoyer confirmation WhatsApp",
    convertToWorkOrder: "Convertir en ordre de travail",
    bookedOn: "Réservé",
    minAppointment: "min rendez-vous",
    liveRefreshes: "En direct · rafraîchit toutes les 30s",
    updating: "mise à jour…",
    refreshBtn: "Actualiser",
    qrCode: "Code QR",
    appointmentsCheckedIn: "Rendez-vous enregistrés",
    walkInsLabel: "Sans rendez-vous",
    totalCheckins: "Total",
    noCheckinsToday: "Aucun enregistrement aujourd'hui",
    shareQrCode: "Partagez le code QR avec les clients pour recevoir des enregistrements",
    showQrCode: "Afficher le code QR",
    customerCheckinQr: "QR d'enregistrement client",
    copyLink: "Copier le lien",
    createWorkOrderModal: "Créer un ordre de travail",
    deviceBrandLabel: "Marque",
    deviceModelLabel: "Modèle",
    workOrderCreated: "✓ Ordre de travail créé",
    // Reports page
    reportsSubtitle: "Résumé mensuel des revenus, dépenses et bénéfices",
    exportPdf: "Exporter PDF",
    loadingReport: "Chargement du rapport...",
    yearlySummary: "Résumé",
    collectedLabel: "Collecté",
    outstandingLabel: "Impayé",
    uncollected: "non collecté",
    totalCosts: "coûts totaux",
    ordersLabel: "Ordres",
    monthByMonth: "Récapitulatif mensuel",
    monthLabel: "Mois",
    collRate: "Taux coll.",
    netProfit: "Bénéfice net",
    noDataForYear: "Aucune donnée pour",
    totalRow: "Total",
    referralSourcesTitle: "Sources de référence",
    referralSubtitle: "Quels canaux apportent le plus de clients et de revenus.",
    fromLabel: "Du",
    toLabel: "Au",
    applyBtn: "Appliquer",
    clearBtn: "Effacer",
    loadingLabel: "Chargement...",
    noReferralData: "Aucune donnée de source de référence. Commencez à sélectionner une source lors de la création d'ordres.",
    sourceHeader: "Source",
    ordersHeader: "Ordres",
    shareHeader: "Part",
    revenueHeader: "Revenus",
    avgOrderHeader: "Ordre moy.",
    accountingExport: "Export comptable",
    accountingSubtitle: "Exportez les paiements, dépenses et commissions pour votre logiciel comptable.",
    thisMonthLabel: "Ce mois",
    thisYearLabel: "Cette année",
    lastYearLabel: "Année dernière",
    preparingLabel: "Préparation…",
    partsReport: "Rapport pièces",
    totalPartsUsed: "Total pièces utilisées",
    partsRevenue: "Revenus pièces",
    partsConsumption: "Consommation de pièces",
    noPartsThisPeriod: "Aucune donnée pour cette période.",
    timesUsed: "Fois utilisé",
    stockAdjustmentHistory: "Historique ajustements stock",
    noAdjustments: "Aucun ajustement enregistré.",
    typeHeader: "Type",
    qtyHeader: "Qté",
    reasonHeader: "Raison",
    byHeader: "Par",
    // Suppliers page
    suppliersSubtitle: "Gérer les fournisseurs et bons de commande",
    addSupplier: "Ajouter fournisseur",
    newSupplier: "Nouveau fournisseur",
    saveSupplier: "Enregistrer fournisseur",
    noSuppliersYet: "Aucun fournisseur",
    addFirstSupplier: "Ajoutez votre premier fournisseur pour créer des bons de commande.",
    searchSuppliers: "Rechercher par nom, téléphone ou email...",
    purchaseOrders: "Bons de commande",
    noPurchaseOrders: "Aucun bon de commande",
    createPoFromTab: "Créez un bon de commande depuis l'onglet Fournisseurs.",
    newPurchaseOrder: "Nouveau bon de commande",
    viewOrders: "Voir les ordres",
    selectPart: "Sélectionner pièce...",
    addAnotherPart: "+ Ajouter une autre pièce",
    notesOptional: "Notes (optionnel)",
    createDraftPo: "Créer brouillon BC",
    editPurchaseOrder: "Modifier bon de commande",
    markSent: "Marquer envoyé",
    markReceived: "Marquer reçu",
    allSuppliersOption: "Tous les fournisseurs",
    // POS page
    posTitle: "Point de vente",
    ordersReadyPickup: "ordres prêts pour récupération",
    noOrdersWaiting: "Aucun ordre en attente",
    allDelivered: "Tous les ordres terminés ont été livrés",
    checkoutTitle: "Caisse",
    orderTotal: "Total de l'ordre",
    alreadyCollected: "Déjà collecté",
    balanceDue: "Reste à payer",
    paymentMethod: "Mode de paiement",
    customerPays: "Le client paie",
    changeToGive: "Monnaie à rendre",
    noChangeDue: "Pas de monnaie",
    orderFullyPaid: "Ordre entièrement payé ✓",
    tapDeliver: "Appuyez sur Livrer pour finaliser",
    markAsDelivered: "✓ Marquer comme livré",
    printReceipt: "Imprimer reçu",
    selectAnOrder: "Sélectionner un ordre",
    tapDoneOrder: "Appuyez sur un ordre TERMINÉ pour encaisser",
    todayLabel: "Aujourd'hui",
    // Expenses page
    expensesSubtitle: "Suivez les dépenses de votre boutique",
    exportCsv: "Exporter CSV",
    addExpense: "Ajouter dépense",
    totalExpenses: "Total des dépenses",
    newExpense: "Nouvelle dépense",
    titleLabel: "Titre",
    amountLabel: "Montant",
    categoryLabel: "Catégorie",
    noteLabel: "Note",
    saveExpense: "Enregistrer dépense",
    searchExpensesByTitle: "Rechercher par titre ou note...",
    noMatchingExpenses: "Aucune dépense correspondante",
    noExpensesYet: "Aucune dépense",
    noExpensesDesc: "Suivez loyer, salaires, fournitures pour avoir une vision claire des coûts.",
    addFirstExpense: "+ Ajouter première dépense",
    // Shifts page
    shiftsSubtitle: "Suivre les heures de tout le personnel",
    shiftsSubtitleOwn: "Suivre vos heures de travail",
    currentlyWorking: "En cours de travail",
    clockOut: "Pointer sortie",
    notClockedIn: "Non pointé",
    clockIn: "Pointer entrée",
    clockingIn: "Pointage…",
    thisWeek: "Cette semaine",
    shiftsHistory: "Historique",
    shiftsTotal: "quarts total",
    noShiftsYet: "Aucun quart enregistré",
    clockInToStart: "Pointez l'entrée pour commencer le suivi",
    engineerHeader: "Technicien",
    clockInHeader: "Entrée",
    clockOutHeader: "Sortie",
    durationHeader: "Durée",
    notesHeader: "Notes",
    activeStatus: "Actif",
    // New Work Order page
    newWorkOrderTitle: "Nouvel ordre de travail",
    hideTemplates: "Masquer modèles",
    useTemplate: "Utiliser modèle",
    templateApplied: "Modèle appliqué",
    step1DeviceInfo: "Appareil",
    step2Customer: "Client",
    step3FaultPhotos: "Panne & Photos",
    fillRequiredFields: "Veuillez remplir tous les champs obligatoires.",
    devicePhotos: "Photos de l'appareil",
    devicePhotosDesc: "Documentez l'état lors de la réception — protège contre les litiges",
    addPhotos: "Ajouter photos",
    clickToAddPhotos: "Cliquez pour ajouter des photos",
    photoFrontBack: "Face, dos, côtés, dommages existants",
    photoRequired: "⚠ Photo requise",
    atLeastOnePhoto: "Au moins une photo est requise",
    addMore: "Ajouter plus",
    returningCustomer: "👤 Client existant",
    useThisCustomer: "Utiliser ce client",
    totalOrdersLabel: "Total ordres",
    lastVisitLabel: "Dernière visite",
    faultService: "Panne & Service",
    faultDescriptionLabel: "Description de la panne *",
    describeFault: "Décrivez la panne...",
    aiRepairEstimate: "Estimation IA",
    estDuration: "Durée est.",
    costRange: "Fourchette de coût",
    likelyParts: "Pièces probables",
    noneExpected: "Aucune attendue",
    successRate: "Taux de succès",
    aiDisclaimer: "Les estimations IA sont indicatives et peuvent varier selon l'état réel.",
    appearanceLabel: "Apparence",
    repairTypeLabel: "Type de réparation",
    serviceTypeLabel: "Type de service",
    faultLevelLabel: "Niveau de panne",
    branchLabel: "Succursale",
    noBranch: "— Aucune succursale —",
    howDidTheyFind: "Comment nous ont-ils trouvés ?",
    selectSource: "— Sélectionner source —",
    referredBy: "Référé par (nom du client)",
    remarksLabel: "Remarques",
    additionalRemarks: "Remarques supplémentaires...",
    createWorkOrderBtn: "Créer l'ordre de travail",
    // Edit Work Order page
    editWorkOrderTitle: "Modifier l'ordre de travail",
    adminOnly: "(Admin uniquement)",
    underWarranty: "Sous garantie",
    failedToSave: "Échec de la sauvegarde",
    deviceIsUnderWarranty: "L'appareil est sous garantie",

    // ── Branches page ──────────────────────────────────────────
    manageBranchesSubtitle: "Gérez plusieurs emplacements sous une boutique",
    addBranch: "Ajouter succursale",
    totalBranches: "Total succursales",
    active: "Actif",
    totalStaff: "Total personnel",
    newBranch: "Nouvelle succursale",
    branchName: "Nom de la succursale",
    address: "Adresse",
    branchManager: "Responsable de succursale",
    noneOption: "— Aucun —",
    createBranch: "Créer succursale",
    loading: "Chargement…",
    noBranchesYet: "Aucune succursale",
    createFirstBranch: "Créez votre première succursale pour gérer plusieurs emplacements",
    staff: "Personnel",
    workOrdersCount: "Ordres de travail",
    partsCount: "Pièces",
    editBranch: "Modifier succursale",
    manager: "Responsable",
    deleteBranch: "Supprimer la succursale ?",
    deleteBranchWarning: "Les ordres, techniciens et pièces liés seront désassignés mais non supprimés.",
    deleteBranchConfirm: "Supprimer succursale",
    assignEngineersLabel: "Assigner techniciens",
    noEngineersFound: "Aucun technicien trouvé",
    engineerUnassigned: "Technicien désassigné",
    engineerAssigned: "Technicien assigné",
    branchCreated: "Succursale créée",
    branchUpdated: "Succursale mise à jour",
    branchDeleted: "Succursale supprimée",

    // ── Certification page ──────────────────────────────────────
    shopCertification: "Certification boutique",
    certSubtitle: "Attribuée automatiquement selon les réparations, évaluations et qualité.",
    couldNotLoadCert: "Impossible de charger les données de certification.",
    noCertYet: "Aucune certification",
    noCertDesc: "Effectuez 10+ réparations avec une note moyenne ≥3,5 pour obtenir le Bronze.",
    downloadBadge: "Télécharger badge",
    earnedDate: "Obtenu le",
    activeCertification: "Certification active",
    workToward: "Viser",
    certNext: "ensuite",
    completedRepairs: "Réparations terminées",
    avgRating: "Note moyenne",
    bounceRate: "Taux de retour",
    nextGoal: "Prochain objectif",
    achieved: "✓ Atteint",
    completedRepairsLabel: "Réparations terminées",
    avgRatingLabel: "Note moyenne",
    bounceRateLower: "Taux de retour (plus bas = mieux)",
    certAutoCalc: "Les certifications sont calculées automatiquement à chaque fois qu'un ordre est marqué",
    certFree: "Toutes les certifications sont gratuites et permanentes tant que votre boutique remplit les critères.",

    // ── Contracts page ──────────────────────────────────────────
    maintenanceContracts: "Contrats de maintenance",
    contractsSubtitle: "Accords de service récurrents avec génération automatique d'ordres",
    newContract: "Nouveau contrat",
    activeContracts: "Contrats actifs",
    monthlyRevenue: "Revenus mensuels",
    annualRevenue: "Revenus annuels",
    dueForBilling: "À facturer",
    loadingContracts: "Chargement des contrats…",
    noContractsYet: "contrats",
    createContractHint: "Créez un contrat pour suivre les revenus de maintenance récurrents",
    customerPhone: "Téléphone du client",
    deviceBrand: "Marque de l'appareil",
    deviceModel: "Modèle de l'appareil",
    serviceDescription: "Description du service",
    monthlyPrice: "Prix mensuel",
    startDate: "Date de début",
    endDate: "Date de fin (optionnel)",
    notes: "Notes",
    internalNotes: "Notes internes",
    createContract: "Créer contrat",
    editContract: "Modifier contrat",
    contractStatus: "Statut",
    pause: "Suspendre",
    resume: "Reprendre",
    dismiss: "Ignorer",
    billedBanner: "facturé(s) — ordres de travail créés automatiquement.",
    nextBilling: "Prochain :",
    endsOn: "Fin le",

    // ── CSV page ───────────────────────────────────────────────
    csvImportTitle: "Import CSV",
    csvImportSubtitle: "Importez en masse des pièces ou clients depuis un tableur",
    whatAreYouImporting: "Que souhaitez-vous importer ?",
    needTemplate: "Besoin d'un modèle ?",
    downloadTemplate: "Télécharger le modèle",
    uploadCsvFile: "Télécharger un fichier CSV",
    dropCsvHere: "Déposez votre CSV ici, ou cliquez pour parcourir",
    csvFilesOnly: "Fichiers .csv uniquement",
    clickToChange: "Ko · Cliquer pour changer",
    nextMapColumns: "Suivant : Mapper les colonnes →",
    mapColumns: "Mapper les colonnes",
    mapColumnsHint: "Associez vos colonnes CSV aux champs attendus. Mapping automatique si possible.",
    rowsDetected: "lignes détectées",
    fieldCol: "Champ",
    csvColumn: "Colonne CSV",
    sampleValue: "Exemple",
    requiredField: "obligatoire",
    skipOption: "— ignorer —",
    preview: "Aperçu",
    firstRows: "premières",
    ofLabel: "sur",
    rowsLabel: "lignes",
    readyLabel: "prêts",
    willBeSkipped: "seront ignorés",
    importingLabel: "Importation…",
    importRows: "Importer",
    importAnotherFile: "Importer un autre fichier",
    totalRowsLabel: "Total lignes",
    importedLabel: "Importé",
    skippedLabel: "Ignoré",
    allRowsImported: "Toutes les lignes importées avec succès !",
    errorsLabel: "Erreurs",
    rowsSkipped: "lignes ignorées",
    downloadErrorReport: "⬇ Télécharger rapport d'erreurs",
    rowCol: "Ligne",
    reasonLabel: "Raison",
    dataLabel: "Données",

    // ── Customer detail page ────────────────────────────────────
    repeatCustomer: "Client régulier",
    customerInfo: "Infos client",
    summary: "Résumé",
    totalSpent: "Total dépensé",
    collectedLabel2: "Perçu",
    outstanding2: "Solde dû",
    teamNotes: "Notes d'équipe",
    internalOnly: "Interne uniquement",
    addNoteHint: "Ajouter une note sur ce client... (Ctrl+Entrée pour enregistrer)",
    addNote: "Ajouter note",
    noNotesYet: "Aucune note. Ajoutez-en une ci-dessus.",
    repairHistory: "Historique des réparations",
    noOrdersFound: "Aucun ordre trouvé.",
    snCol: "N° série",
    partsCol: "Pièces",

    // ── Engineers / Commissions page ────────────────────────────
    engineerCommissions: "Commissions techniciens",
    commissionsSubtitle: "Suivi mensuel des commissions par technicien",
    totalRevenue: "Revenus totaux",
    totalCommissions: "Total commissions",
    saveSnapshot: "💾 Sauvegarder",
    engineerCol: "Technicien",
    roleCol: "Rôle",
    ordersCol: "Ordres",
    revenueCol: "Revenus",
    commissionRate: "Taux commission",
    commissionAmount: "Montant commission",
    lockedCol: "Verrouillé ?",
    noEngineersFoundComm: "Aucun technicien trouvé.",
    commissionSaved: "Instantané de commission enregistré.",
    commissionFailed: "Échec de l'enregistrement.",
    commissionFormula: "La commission est calculée comme :",
    commissionFormulaDetail: "pour les ordres DONE ou DELIVERED, mis à jour en",
    useSnapshotHint: "Utilisez \"Sauvegarder\" pour verrouiller les chiffres actuels.",
    savedLabel: "Enregistré",

    // ── Engineers page ─────────────────────────────────────────
    teamPerformance: "Aperçu des performances de l'équipe",
    commissionsLink: "💸 Commissions",
    addEngineer: "Ajouter technicien",
    newEngineer: "Nouveau technicien",
    fullName: "Nom complet",
    temporaryPassword: "Mot de passe temporaire",
    noTeamMembersYet: "Aucun membre d'équipe",
    addEngineersHint: "Ajoutez des techniciens pour qu'ils puissent se connecter et travailler sur les ordres.",
    totalRevenueStat: "Revenus totaux",
    commissionStat: "Commission",
    assigned: "Assigné",
    completed: "Terminé",
    deliveredStat: "Livré",
    cancelledStat: "Annulé",
    bounces: "Retours",
    avgTat: "TAT moy.",
    completionRate: "Taux de complétion",
    newPassword: "Nouveau mot de passe",
    leaveBlank: "laisser vide pour conserver",
    commissionRatePct: "Taux commission (%)",
    failedToLoad: "Échec du chargement",
    allFieldsRequired: "Tous les champs sont obligatoires",

    // ── Messages page ──────────────────────────────────────────
    messagesTitle: "Messages",
    messagesSubtitle: "Conversations clients sur tous les ordres de travail",
    noMessagesYet: "Aucun message.",
    messagesWillAppear: "Les messages clients apparaîtront ici.",
    customerLabel: "Client :",
    youLabel: "Vous :",

    // ── Pricing page ───────────────────────────────────────────
    pricingEngine: "Moteur de tarification",
    pricingSubtitle: "Suivez, analysez et optimisez vos prix de réparation",
    addHistoricalPrice: "+ Ajouter prix historique",
    addHistoricalPricingEntry: "Ajouter entrée de tarification historique",
    priceCharged: "Prix facturé",
    partsCost: "Coût pièces",
    customerAccepted: "Client accepté ?",
    yesOption: "Oui",
    noRejected: "Non (refusé / parti)",
    saveEntry: "Enregistrer",
    repairTypesTracked: "Types de réparation suivis",
    totalEntries: "Total entrées",
    mostDone: "Le plus fréquent",
    underpricedRepairs: "Réparations sous-tarifées",
    allRepairTypes: "Tous types de réparation",
    analyticsTab: "Analytique",
    searchRepairType: "Rechercher type de réparation…",
    typesLabel: "types",
    noPricingDataYet: "Aucune donnée de tarification.",
    pricingAutoSaved: "Les prix sont enregistrés automatiquement lors de la livraison, ou ajoutez-les manuellement ci-dessus.",
    minLabel: "Min",
    averageLabel: "Moyenne",
    maxLabel: "Max",
    marginLabel: "Marge",
    mostProfitable: "Réparations les plus rentables",
    leastProfitable: "Moins rentables — Envisagez de hausser les prix",
    leastProfitableHint: "Réparations où votre marge est la plus faible. Envisagez d'augmenter les prix ou de réduire le coût des pièces.",
    underpricedTitle: "Réparations sous-tarifées",
    underpricedHint: "Ces réparations ont une marge inférieure à 20 % — vous perdez peut-être de l'argent après pièces + main-d'œuvre.",
    raiseTitle: "Opportunité — Envisagez de hausser les prix",
    raiseHint: "Ces réparations ont un taux d'acceptation ≥90 % — le marché peut supporter un prix plus élevé.",
    dropTitle: "Faible acceptation — Revoir ou abandonner",
    dropHint: "Faible taux d'acceptation : les clients rejettent les devis. Envisagez de baisser le prix ou d'arrêter.",
    notEnoughData: "Pas assez de données.",
    notEnoughDataFull: "Pas assez de données",
    notEnoughDataDesc: "Livrez plus d'ordres ou ajoutez des entrées historiques pour débloquer l'analytique de tarification.",

    // ── Ratings page ──────────────────────────────────────────
    customerSatisfaction: "Satisfaction client",
    ratingsSubtitle: "Évaluations collectées après livraison",
    reviewsLabel: "avis",
    noRatingsYet: "Aucune évaluation",
    ratingsWillAppear: "Les évaluations clients apparaissent ici après la livraison des ordres.",
    failedLoadRatings: "Échec du chargement des évaluations",

    // ── Shops page ────────────────────────────────────────────
    shopManagement: "Gestion des boutiques",
    shopManagementSubtitle: "Gérez vos paramètres et toutes les boutiques locataires",
    myShopSettings: "Mes paramètres boutique",
    shopName: "Nom de la boutique",
    savedSuccessfully: "✓ Enregistré avec succès",
    allTenantShops: "Toutes les boutiques locataires",
    shopCol: "Boutique",
    ownerCol: "Propriétaire",
    ordersShopCol: "Ordres",
    planCol: "Plan",
    trialEnds: "Fin essai",
    actionsCol: "Actions",
    noShopsYet: "Aucune boutique.",
    activate: "Activer",
    trialBtn: "Essai",
    suspendBtn: "Suspendre",
    superAdminRequired: "Accès super admin requis.",
    trialDaysLeft: "Essai :",
    daysLeft: "jours restants",
    sinceLabel: "Depuis",

    // ── Templates page ────────────────────────────────────────
    workOrderTemplates: "Modèles d'ordres de travail",
    templatesSubtitle: "Pré-remplissez les réparations courantes pour gagner du temps",
    newTemplate: "Nouveau modèle",
    templateName: "Nom du modèle",
    categoryLabel2: "Catégorie",
    noCategory: "Sans catégorie",
    estimatedDuration: "Durée estimée",
    minutes: "minutes",
    defaultPrice: "Prix par défaut",
    defaultSpareParts: "Pièces par défaut",
    defaultLineItems: "Lignes par défaut (Main-d'œuvre, Services)",
    laborFeeHint: "ex. Frais main-d'œuvre",
    saveTemplate: "Enregistrer modèle",
    noTemplatesYet: "Aucun modèle",
    noTemplatesDesc: "Les modèles permettent de pré-remplir les réparations courantes en un clic.",
    createFirstTemplate: "+ Créer premier modèle",
    noTemplatesInCategory: "Aucun modèle dans",
    tryClearFilter: "Essayez une autre catégorie ou effacez le filtre.",
    deleteTemplateConfirm: "Supprimer ce modèle ?",

    // ── Warranties page ───────────────────────────────────────
    warrantiesTitle: "Garanties",
    warrantiesSubtitle: "Suivez le statut des garanties sur tous les appareils réparés",
    underWarrantyLabel: "sous garantie",
    expiringSoon: "Expire bientôt",
    within30Days: "dans les 30 jours",
    expiredLabel: "Expirée",
    pastEndDate: "après la date de fin",
    tabActive: "Actives",
    tabExpiringSoon: "Expirent bientôt",
    tabExpired: "Expirées",
    noActiveWarranties: "Aucune garantie active",
    noActiveWarrantiesDesc: "Les garanties apparaissent ici dès qu'un ordre a une date de fin de garantie.",
    nothingExpiringSoon: "Rien n'expire bientôt",
    nothingExpiringSoonDesc: "Tout est clair — aucune garantie n'expire dans les 30 prochains jours.",
    noExpiredWarranties: "Aucune garantie expirée",
    noExpiredWarrantiesDesc: "Les garanties expirées apparaîtront ici une fois leur date de fin passée.",
    warrantyPeriod: "Période de garantie",
    remainingLabel: "Restant",
    unassigned: "Non assigné",
    warrantyEnds: "Fin garantie",
    startedLabel: "Début",
    repairedLabel: "Réparé",

    // ── Academy page ──────────────────────────────────────────
    academyTitle: "🎓 FixFlow Académie",
    academySubtitle: "Cours gratuits pour maîtriser votre atelier de réparation",
    enrolledLabel: "Inscrit",
    completedCourses: "Terminé",
    lessonsCount: "leçons",
    courseContent: "Contenu du cours",
    enrollFree: "S'inscrire gratuitement et commencer",
    enrolling: "Inscription…",
    reviewCourse: "Revoir le cours",
    continueCourse: "Continuer →",
    startLearning: "Commencer →",
    certificateEarned: "Certificat obtenu · Voir",
    certOfCompletion: "Certificat de réussite obtenu",
    viewCertificate: "Voir le certificat →",
    backToCourse: "Retour au cours →",
    markComplete: "Marquer terminé",
    markCompleteSaving: "Enregistrement…",
    markCompleteFinish: "Marquer terminé & finir →",
    courseNotFound: "Cours introuvable",
    lessonNotFound: "Leçon introuvable.",
    courseOutline: "Plan du cours",
    totalMinutes: "minutes au total",

    // ── Health Report page ────────────────────────────────────
    deviceHealthReport: "Rapport de santé de l'appareil",
    postRepairAssessment: "Évaluation de l'état post-réparation",
    failedLoadHealthReport: "⚠️ Échec du chargement du rapport de santé",
    goBack: "Retour",
    orderNotFound: "Ordre introuvable",
    printSavePdf: "🖨 Imprimer / Enregistrer PDF",
    repairSummary: "Résumé de la réparation",
    issueReported: "Problème signalé",
    receivedLabel2: "Reçu le",
    completedLabel: "Terminé le",
    technicianLabel: "Technicien",
    partsReplaced: "Pièces remplacées",
    deviceConditionAssessment: "Évaluation de l'état de l'appareil",
    issuesLabel: "Problèmes",
    discountLabel: "Remise",
    subtotalLabel: "Sous-total",
    taxLabel: "taxe",
    totalInclTax: "Total TTC",
    healthReportFooter: "Ce rapport certifie que l'appareil a été réparé et testé par",
    generatedBy: "Généré par FixFlow ·",
  },
  ar: {
    workOrders: "أوامر العمل",
    spareParts: "قطع الغيار",
    customers: "العملاء",
    warranties: "الضمانات",
    satisfaction: "الرضا",
    csvImport: "استيراد CSV",
    analytics: "التحليلات",
    engineers: "المهندسون",
    reports: "التقارير",
    templates: "القوالب",
    shops: "المتاجر",
    expenses: "المصاريف",
    settings: "الإعدادات",
    appointments: "المواعيد",
    suppliers: "الموردون",
    certification: "الشهادة",
    messages: "الرسائل",
    pricing: "التسعير",
    contracts: "العقود",
    branches: "الفروع",
    pointOfSale: "نقطة البيع",
    shifts: "الورديات",
    academy: "الأكاديمية",
    notifications: "الإشعارات",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الداكن",
    installApp: "تثبيت التطبيق",
    logout: "تسجيل الخروج",
    orders: "الطلبات",
    parts: "القطع",
    markAllRead: "تحديد الكل كمقروء",
    noNotifications: "لا توجد إشعارات",
    sessionExpiring: "انتهاء الجلسة قريباً",
    sessionWarningBody: "سيتم تسجيل خروجك خلال {time} بسبب عدم النشاط.",
    stayLoggedIn: "البقاء متصلاً",
    // Dashboard / Work Orders list
    newWorkOrder: "أمر جديد",
    searchWorkOrders: "البحث بالعميل، الهاتف، الجهاز...",
    all: "الكل",
    noContact3d: "بلا تواصل 3 أيام+",
    allBranches: "كل الفروع",
    totalOrders: "إجمالي الأوامر",
    received: "مستلم",
    inProgress: "قيد التنفيذ",
    ready: "جاهز",
    revenue: "الإيرادات",
    delivered: "تم التسليم",
    cancelled: "ملغى",
    todaysAppointments: "مواعيد اليوم",
    noAppointmentsToday: "لا مواعيد اليوم",
    recentActivity: "النشاط الأخير",
    noRecentActivity: "لا نشاط حديث",
    viewAll: "عرض الكل",
    noOrdersMatchSearch: "لا توجد أوامر تطابق بحثك",
    noWorkOrdersYet: "لا توجد أوامر عمل بعد",
    tryDifferentSearch: "جرب بحثاً أو فلتراً مختلفاً",
    createFirstWorkOrder: "أنشئ أمر عملك الأول للبدء",
    selectAll: "تحديد الكل",
    selected: "محدد",
    changeStatus: "تغيير الحالة...",
    apply: "تطبيق",
    assignEngineer: "تعيين تقني...",
    assign: "تعيين",
    exportBtn: "تصدير",
    deleteBtn: "حذف",
    columns: "الأعمدة",
    orderHash: "رقم الأمر",
    customer: "العميل",
    device: "الجهاز",
    fault: "العطل",
    status: "الحالة",
    assignedTo: "مُعيَّن لـ",
    total: "المجموع",
    date: "التاريخ",
    view: "عرض",
    prev: "السابق",
    next: "التالي",
    page: "صفحة",
    showing: "عرض",
    deleteWorkOrders: "حذف أوامر العمل",
    cannotBeUndone: "لا يمكن التراجع عن هذا.",
    cancel: "إلغاء",
    deleting: "جارٍ الحذف...",
    morningBriefing: "إحاطة الصباح",
    justNow: "الآن",
    mAgo: "د",
    hAgo: "س",
    dAgo: "ي",
    // Work Order detail
    back: "رجوع",
    print: "طباعة",
    share: "مشاركة",
    whatsapp: "واتساب",
    sendReminder: "إرسال تذكير",
    healthReport: "تقرير الصحة",
    edit: "تعديل",
    reportBounce: "الإبلاغ عن عودة",
    startDiagnosis: "بدء التشخيص",
    startRepair: "بدء الإصلاح",
    markDone: "تحديد كمنتهٍ",
    markDelivered: "تحديد كمسلَّم",
    deviceInformation: "معلومات الجهاز",
    brand: "الماركة",
    model: "الموديل",
    serialNumber: "الرقم التسلسلي",
    imei: "الرقم التعريفي",
    warrantyStart: "بداية الضمان",
    warrantyEnd: "نهاية الضمان",
    customerInformation: "معلومات العميل",
    draftMessage: "صياغة رسالة",
    name: "الاسم",
    phone: "الهاتف",
    email: "البريد الإلكتروني",
    faultAndService: "العطل والخدمة",
    serviceType: "نوع الخدمة",
    repairType: "نوع الإصلاح",
    faultLevel: "مستوى العطل",
    appearance: "المظهر",
    faultDescription: "وصف العطل",
    remarks: "ملاحظات",
    addPart: "إضافة قطعة",
    part: "القطعة",
    quantity: "الكمية",
    price: "السعر",
    noPartsAdded: "لم تُضَف أي قطع بعد.",
    attachments: "المرفقات",
    uploadFile: "رفع ملف",
    noAttachments: "لا توجد مرفقات بعد.",
    save: "حفظ",
    saving: "جارٍ الحفظ...",
    adding: "جارٍ الإضافة...",
    // Customers page
    addCustomer: "إضافة عميل",
    searchCustomers: "البحث عن العملاء...",
    noCustomersFound: "لا عملاء",
    // Spare Parts page
    searchParts: "البحث عن قطع الغيار...",
    stock: "المخزون",
    unitPrice: "سعر الوحدة",
    partNumber: "رقم القطعة",
    noPartsFound: "لا قطع غيار",
    lowStock: "مخزون منخفض",
    // Analytics page
    analyticsSubtitle: "الإيرادات والمصاريف والأرباح والرؤى",
    days7: "7 أيام",
    days30: "30 يوماً",
    days90: "90 يوماً",
    allTime: "كل الوقت",
    analyticsCSV: "CSV التحليلات",
    tabOverview: "نظرة عامة",
    tabBenchmarks: "المعايير",
    tabCopilot: "المساعد",
    kpiTotalOrders: "إجمالي الأوامر",
    kpiCollected: "المحصَّل",
    kpiExpenses: "المصاريف",
    kpiNetProfit: "صافي الربح",
    kpiOutstanding: "المعلق",
    kpiActive: "نشط",
    kpiRate: "نسبة",
    kpiMargin: "هامش",
    kpiUnpaid: "غير مدفوع",
    kpiTotalCosts: "إجمالي التكاليف",
    momTitle: "مقارنة شهرية",
    collectionRate: "نسبة التحصيل",
    revenueExpensesProfit: "الإيرادات والمصاريف والربح",
    revenueExpensesSubtitle: "المفوتر مقابل المحصَّل مقابل المصاريف مقابل صافي الربح",
    noDataYet: "لا توجد بيانات.",
    workOrdersVolume: "حجم أوامر العمل",
    ordersPerPeriod: "عدد الأوامر لكل فترة",
    ordersByStatus: "الأوامر حسب الحالة",
    currentDistribution: "التوزيع الحالي",
    noData: "لا بيانات.",
    engineerLeaderboard: "ترتيب المهندسين",
    engineerLeaderboardSubtitle: "الأداء مرتباً حسب الأوامر المنجزة",
    noEngineersYet: "لا مهندسين بعد.",
    topSparePartsUsed: "أكثر قطع الغيار استخداماً",
    topPartsSubtitle: "القطع الأكثر استخداماً في هذه الفترة",
    noPartsDataYet: "لا توجد بيانات قطع بعد.",
    stockStatus: "حالة المخزون",
    partsBelowFive: "قطع أقل من 5 وحدات",
    allPartsWellStocked: "جميع القطع متوفرة بكميات جيدة",
    slaCompliance: "الالتزام بمعايير SLA",
    slaSubtitle: "الأوامر المنجزة ضمن موعدها",
    noSlaOrders: "لا توجد أوامر منجزة بمواعيد SLA بعد.",
    slaMetLabel: "SLA مستوفى",
    slaBreachedLabel: "متجاوَز",
    referralSources: "مصادر الإحالة",
    howCustomersFind: "كيف يجدك العملاء",
    loyaltyMilestones: "معالم الولاء",
    loyaltySubtitle: "أبرز مؤشرات مشاركة العملاء",
    anniversariesThisMonth: "أعياد ميلاد هذا الشهر",
    tenPlusCustomers: "عملاء +10 أوامر",
    goldVip: "VIP ذهبي (+6 أوامر)",
    somethingWentWrong: "حدث خطأ ما",
    tryAgain: "حاول مجدداً",
    loadingAnalysis: "تحليل بيانات 90 يوماً…",
    generateAnalysis: "توليد التحليل",
    revenueCopilot: "مساعد الإيرادات",
    copilotDescription: "تقرير الذكاء التجاري لـ 90 يوماً",
    // Appointments page
    todaysCheckins: "تسجيلات حضور اليوم",
    allAppointments: "جميع المواعيد",
    calendarView: "التقويم",
    listView: "القائمة",
    checkinsView: "تسجيل الحضور",
    newAppointment: "موعد جديد",
    appointmentDetails: "تفاصيل الموعد",
    editAppointment: "تعديل الموعد",
    newAppointmentTitle: "موعد جديد",
    customerName: "اسم العميل",
    dateAndTime: "التاريخ والوقت",
    issueLabel: "المشكلة",
    duration: "المدة",
    createAppointment: "إنشاء موعد",
    creating: "جارٍ الإنشاء…",
    noAppointmentsStatus: "لا مواعيد بهذا الحالة",
    noAppointmentsYet: "لا مواعيد بعد",
    dateTimeHeader: "التاريخ والوقت",
    actionsHeader: "الإجراءات",
    confirmAction: "تأكيد",
    cancelAction: "إلغاء",
    reschedule: "إعادة جدولة",
    newDateTime: "تاريخ ووقت جديد",
    confirmReschedule: "تأكيد إعادة الجدولة",
    savingLabel: "جارٍ الحفظ…",
    saveChanges: "حفظ التغييرات",
    sendWhatsApp: "إرسال تأكيد واتساب",
    convertToWorkOrder: "تحويل إلى أمر عمل",
    bookedOn: "محجوز",
    minAppointment: "دقيقة موعد",
    liveRefreshes: "مباشر · يتحدث كل 30 ثانية",
    updating: "تحديث…",
    refreshBtn: "تحديث",
    qrCode: "رمز QR",
    appointmentsCheckedIn: "المواعيد المسجلة",
    walkInsLabel: "الزيارات المباشرة",
    totalCheckins: "المجموع",
    noCheckinsToday: "لا تسجيلات حضور اليوم",
    shareQrCode: "شارك رمز QR مع العملاء لبدء تسجيل الحضور",
    showQrCode: "إظهار رمز QR",
    customerCheckinQr: "رمز QR لتسجيل حضور العميل",
    copyLink: "نسخ الرابط",
    createWorkOrderModal: "إنشاء أمر عمل",
    deviceBrandLabel: "الماركة",
    deviceModelLabel: "الموديل",
    workOrderCreated: "✓ تم إنشاء أمر العمل",
    // Reports page
    reportsSubtitle: "ملخص الإيرادات والمصاريف والأرباح الشهرية",
    exportPdf: "تصدير PDF",
    loadingReport: "جارٍ تحميل التقرير...",
    yearlySummary: "الملخص",
    collectedLabel: "المحصَّل",
    outstandingLabel: "المعلق",
    uncollected: "غير محصَّل",
    totalCosts: "إجمالي التكاليف",
    ordersLabel: "الأوامر",
    monthByMonth: "التفصيل الشهري",
    monthLabel: "الشهر",
    collRate: "نسبة التحصيل",
    netProfit: "صافي الربح",
    noDataForYear: "لا توجد بيانات لـ",
    totalRow: "المجموع",
    referralSourcesTitle: "مصادر الإحالة",
    referralSubtitle: "القنوات التي تجلب أكثر العملاء والإيرادات.",
    fromLabel: "من",
    toLabel: "إلى",
    applyBtn: "تطبيق",
    clearBtn: "مسح",
    loadingLabel: "جارٍ التحميل...",
    noReferralData: "لا توجد بيانات مصدر الإحالة. ابدأ باختيار مصدر عند إنشاء الأوامر.",
    sourceHeader: "المصدر",
    ordersHeader: "الأوامر",
    shareHeader: "الحصة",
    revenueHeader: "الإيرادات",
    avgOrderHeader: "متوسط الأمر",
    accountingExport: "تصدير محاسبي",
    accountingSubtitle: "تصدير المدفوعات والمصاريف والعمولات لبرنامج المحاسبة الخاص بك.",
    thisMonthLabel: "هذا الشهر",
    thisYearLabel: "هذه السنة",
    lastYearLabel: "السنة الماضية",
    preparingLabel: "جارٍ التحضير…",
    partsReport: "تقرير القطع",
    totalPartsUsed: "إجمالي القطع المستخدمة",
    partsRevenue: "إيرادات القطع",
    partsConsumption: "استهلاك القطع",
    noPartsThisPeriod: "لا توجد بيانات لهذه الفترة.",
    timesUsed: "مرات الاستخدام",
    stockAdjustmentHistory: "سجل تعديلات المخزون",
    noAdjustments: "لا تعديلات مسجلة.",
    typeHeader: "النوع",
    qtyHeader: "الكمية",
    reasonHeader: "السبب",
    byHeader: "بواسطة",
    // Suppliers page
    suppliersSubtitle: "إدارة الموردين وأوامر الشراء",
    addSupplier: "إضافة مورد",
    newSupplier: "مورد جديد",
    saveSupplier: "حفظ المورد",
    noSuppliersYet: "لا موردون بعد",
    addFirstSupplier: "أضف مورداً أولاً لبدء إنشاء أوامر الشراء.",
    searchSuppliers: "البحث بالاسم أو الهاتف أو البريد الإلكتروني...",
    purchaseOrders: "أوامر الشراء",
    noPurchaseOrders: "لا أوامر شراء",
    createPoFromTab: "أنشئ أمر شراء من تبويب الموردين.",
    newPurchaseOrder: "أمر شراء جديد",
    viewOrders: "عرض الأوامر",
    selectPart: "اختر قطعة...",
    addAnotherPart: "+ إضافة قطعة أخرى",
    notesOptional: "ملاحظات (اختياري)",
    createDraftPo: "إنشاء مسودة أمر شراء",
    editPurchaseOrder: "تعديل أمر الشراء",
    markSent: "تحديد كمُرسَل",
    markReceived: "تحديد كمُستلَم",
    allSuppliersOption: "جميع الموردين",
    // POS page
    posTitle: "نقطة البيع",
    ordersReadyPickup: "أوامر جاهزة للاستلام",
    noOrdersWaiting: "لا أوامر في الانتظار",
    allDelivered: "تم تسليم جميع الأوامر المنتهية",
    checkoutTitle: "الدفع",
    orderTotal: "إجمالي الأمر",
    alreadyCollected: "تم تحصيله مسبقاً",
    balanceDue: "المبلغ المستحق",
    paymentMethod: "طريقة الدفع",
    customerPays: "العميل يدفع",
    changeToGive: "الباقي للعميل",
    noChangeDue: "لا يوجد باقٍ",
    orderFullyPaid: "الأمر مدفوع بالكامل ✓",
    tapDeliver: "اضغط تسليم لإتمام التسليم",
    markAsDelivered: "✓ تحديد كمُسلَّم",
    printReceipt: "طباعة الإيصال",
    selectAnOrder: "اختر أمراً",
    tapDoneOrder: "اضغط على أمر منتهٍ لتسليم العميل",
    todayLabel: "اليوم",
    // Expenses page
    expensesSubtitle: "تتبع مصاريف متجرك",
    exportCsv: "تصدير CSV",
    addExpense: "إضافة مصروف",
    totalExpenses: "إجمالي المصاريف",
    newExpense: "مصروف جديد",
    titleLabel: "العنوان",
    amountLabel: "المبلغ",
    categoryLabel: "الفئة",
    noteLabel: "ملاحظة",
    saveExpense: "حفظ المصروف",
    searchExpensesByTitle: "البحث بالعنوان أو الملاحظة...",
    noMatchingExpenses: "لا مصاريف مطابقة",
    noExpensesYet: "لا مصاريف بعد",
    noExpensesDesc: "تتبع الإيجار والرواتب والمستلزمات للحصول على صورة واضحة عن تكاليف متجرك.",
    addFirstExpense: "+ إضافة أول مصروف",
    // Shifts page
    shiftsSubtitle: "تتبع ساعات العمل لجميع الموظفين",
    shiftsSubtitleOwn: "تتبع ساعات عملك",
    currentlyWorking: "في العمل حالياً",
    clockOut: "تسجيل الخروج",
    notClockedIn: "لم يتم تسجيل الحضور",
    clockIn: "تسجيل الحضور",
    clockingIn: "جارٍ التسجيل…",
    thisWeek: "هذا الأسبوع",
    shiftsHistory: "السجل",
    shiftsTotal: "ورديات إجمالاً",
    noShiftsYet: "لم تُسجَّل ورديات بعد",
    clockInToStart: "سجّل حضورك للبدء في تتبع الساعات",
    engineerHeader: "المهندس",
    clockInHeader: "تسجيل الحضور",
    clockOutHeader: "تسجيل الخروج",
    durationHeader: "المدة",
    notesHeader: "الملاحظات",
    activeStatus: "نشط",
    // New Work Order page
    newWorkOrderTitle: "أمر عمل جديد",
    hideTemplates: "إخفاء القوالب",
    useTemplate: "استخدام قالب",
    templateApplied: "تم تطبيق القالب",
    step1DeviceInfo: "معلومات الجهاز",
    step2Customer: "العميل",
    step3FaultPhotos: "العطل والصور",
    fillRequiredFields: "يرجى ملء جميع الحقول المطلوبة.",
    devicePhotos: "صور الجهاز",
    devicePhotosDesc: "وثّق حالة الجهاز عند الاستلام — يحمي من النزاعات",
    addPhotos: "إضافة صور",
    clickToAddPhotos: "انقر لإضافة صور الجهاز",
    photoFrontBack: "الواجهة، الخلف، الجوانب، أي تلف موجود",
    photoRequired: "⚠ صورة الجهاز مطلوبة",
    atLeastOnePhoto: "مطلوبة صورة واحدة على الأقل",
    addMore: "إضافة المزيد",
    returningCustomer: "👤 عميل مُعاد",
    useThisCustomer: "استخدام هذا العميل",
    totalOrdersLabel: "إجمالي الأوامر",
    lastVisitLabel: "آخر زيارة",
    faultService: "العطل والخدمة",
    faultDescriptionLabel: "وصف العطل *",
    describeFault: "صف العطل...",
    aiRepairEstimate: "تقدير إصلاح بالذكاء الاصطناعي",
    estDuration: "المدة المقدرة",
    costRange: "نطاق التكلفة",
    likelyParts: "القطع المحتملة",
    noneExpected: "لا شيء متوقع",
    successRate: "نسبة النجاح",
    aiDisclaimer: "تقديرات الذكاء الاصطناعي استرشادية فقط وقد تختلف حسب الحالة الفعلية.",
    appearanceLabel: "المظهر",
    repairTypeLabel: "نوع الإصلاح",
    serviceTypeLabel: "نوع الخدمة",
    faultLevelLabel: "مستوى العطل",
    branchLabel: "الفرع",
    noBranch: "— بلا فرع —",
    howDidTheyFind: "كيف وجدونا؟",
    selectSource: "— اختر المصدر —",
    referredBy: "أحاله (اسم العميل)",
    remarksLabel: "ملاحظات",
    additionalRemarks: "أي ملاحظات إضافية...",
    createWorkOrderBtn: "إنشاء أمر العمل",
    // Edit Work Order page
    editWorkOrderTitle: "تعديل أمر العمل",
    adminOnly: "(مشرف فقط)",
    underWarranty: "تحت الضمان",
    failedToSave: "فشل الحفظ",
    deviceIsUnderWarranty: "الجهاز تحت الضمان",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

type LanguageContextType = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKey) => string;
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key) => translations.en[key],
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  // Hydrate from localStorage on mount
  useEffect(() => {
    const stored = localStorage.getItem("lang") as Lang | null;
    if (stored && stored in translations) setLangState(stored);
  }, []);

  // Keep <html dir> and <html lang> in sync
  useEffect(() => {
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang]);

  function setLang(l: Lang) {
    setLangState(l);
    localStorage.setItem("lang", l);
  }

  function t(key: TranslationKey): string {
    return (translations[lang] as Record<string, string>)[key] ?? translations.en[key];
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
